//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.05.06 at 12:54:08 PM BST
//

package org.mpxj.edrawproject.schema;

import java.time.LocalTime;
import jakarta.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter4
         extends
            XmlAdapter<String, LocalTime>
{

   @Override public LocalTime unmarshal(String value)
   {
      return (org.mpxj.edrawproject.DatatypeConverter.parseTime(value));
   }

   @Override public String marshal(LocalTime value)
   {
      return (org.mpxj.edrawproject.DatatypeConverter.printTime(value));
   }

}
