//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.01.02 at 04:27:10 PM GMT
//

package org.mpxj.primavera.schema;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for GlobalPrivilegesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GlobalPrivilegesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AddDeleteSecureCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteProjectTemplates" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteRiskCategoriesMatricesAndThresholds" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteGlobalActivityAndAssignmentViewsAndFilters" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteGlobalProjectWBSPortfolioViewsAndFilters" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddGlobalActivityCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddGlobalIssueCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddProjectCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddResourceCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddRoleCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddResources" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AdministerGlobalExternalApplications" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AdministerProjectScheduledServices" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ApproveResourceTimesheets" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AssignSecureCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="DeleteGlobalActivityCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="DeleteGlobalIssueCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="DeleteProjectCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="DeleteResourceCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="DeleteRoleCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="DeleteResources" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteActivityStepTemplates" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteCategoriesAndOverheadCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteCostAccounts" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteCurrencies" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteFinancialPeriodDates" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteFundingSources" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditGlobalActivityCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteGlobalCalendars" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditGlobalChangeDefinitions" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteGlobalDashboards" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditGlobalIssueCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteGlobalPortfolios" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteGlobalReports" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteGlobalResourceAndRoleTeams" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteGlobalScenarios" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditGlobalTrackingLayouts" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteIssueForms" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteMSPTemplates" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteOBS" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditProjectCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditProjectsFromScorecards" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteResourceCalendars" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditResourceCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditRoleCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteResourceCurves" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditResources" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteRoles" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditSecureCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteSecurityProfiles" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteTimesheetPeriodDates" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteUserDefinedFields" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteUserInterfaceViews" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteUsers" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ImportXERMPPMPXandP3" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ImportXML" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ImportXLS" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ViewAllGlobalAndProjectDataViaSDK" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ViewResourceAndRoleCostsAndFinancials" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ViewResourceRoleProficiency" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ViewSecureCodes" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteRateTypesandUnitsofMeasure" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EditApplicationSettings" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ProvisionUsersfromLDAP" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AdministerGlobalScheduledServices" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="AddEditDeleteLocations" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "GlobalPrivilegesType", propOrder =
{
   "addDeleteSecureCodes",
   "addEditDeleteProjectTemplates",
   "addEditDeleteRiskCategoriesMatricesAndThresholds",
   "addEditDeleteGlobalActivityAndAssignmentViewsAndFilters",
   "addEditDeleteGlobalProjectWBSPortfolioViewsAndFilters",
   "addGlobalActivityCodes",
   "addGlobalIssueCodes",
   "addProjectCodes",
   "addResourceCodes",
   "addRoleCodes",
   "addResources",
   "administerGlobalExternalApplications",
   "administerProjectScheduledServices",
   "approveResourceTimesheets",
   "assignSecureCodes",
   "deleteGlobalActivityCodes",
   "deleteGlobalIssueCodes",
   "deleteProjectCodes",
   "deleteResourceCodes",
   "deleteRoleCodes",
   "deleteResources",
   "addEditDeleteActivityStepTemplates",
   "addEditDeleteCategoriesAndOverheadCodes",
   "addEditDeleteCostAccounts",
   "addEditDeleteCurrencies",
   "addEditDeleteFinancialPeriodDates",
   "addEditDeleteFundingSources",
   "editGlobalActivityCodes",
   "addEditDeleteGlobalCalendars",
   "editGlobalChangeDefinitions",
   "addEditDeleteGlobalDashboards",
   "editGlobalIssueCodes",
   "addEditDeleteGlobalPortfolios",
   "addEditDeleteGlobalReports",
   "addEditDeleteGlobalResourceAndRoleTeams",
   "addEditDeleteGlobalScenarios",
   "editGlobalTrackingLayouts",
   "addEditDeleteIssueForms",
   "addEditDeleteMSPTemplates",
   "addEditDeleteOBS",
   "editProjectCodes",
   "editProjectsFromScorecards",
   "addEditDeleteResourceCalendars",
   "editResourceCodes",
   "editRoleCodes",
   "addEditDeleteResourceCurves",
   "editResources",
   "addEditDeleteRoles",
   "editSecureCodes",
   "addEditDeleteSecurityProfiles",
   "addEditDeleteTimesheetPeriodDates",
   "addEditDeleteUserDefinedFields",
   "addEditDeleteUserInterfaceViews",
   "addEditDeleteUsers",
   "importXERMPPMPXandP3",
   "importXML",
   "importXLS",
   "viewAllGlobalAndProjectDataViaSDK",
   "viewResourceAndRoleCostsAndFinancials",
   "viewResourceRoleProficiency",
   "viewSecureCodes",
   "addEditDeleteRateTypesandUnitsofMeasure",
   "editApplicationSettings",
   "provisionUsersfromLDAP",
   "administerGlobalScheduledServices",
   "addEditDeleteLocations"
}) public class GlobalPrivilegesType
{

   @XmlElement(name = "AddDeleteSecureCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addDeleteSecureCodes;
   @XmlElement(name = "AddEditDeleteProjectTemplates", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteProjectTemplates;
   @XmlElement(name = "AddEditDeleteRiskCategoriesMatricesAndThresholds", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteRiskCategoriesMatricesAndThresholds;
   @XmlElement(name = "AddEditDeleteGlobalActivityAndAssignmentViewsAndFilters", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteGlobalActivityAndAssignmentViewsAndFilters;
   @XmlElement(name = "AddEditDeleteGlobalProjectWBSPortfolioViewsAndFilters", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteGlobalProjectWBSPortfolioViewsAndFilters;
   @XmlElement(name = "AddGlobalActivityCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addGlobalActivityCodes;
   @XmlElement(name = "AddGlobalIssueCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addGlobalIssueCodes;
   @XmlElement(name = "AddProjectCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addProjectCodes;
   @XmlElement(name = "AddResourceCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addResourceCodes;
   @XmlElement(name = "AddRoleCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addRoleCodes;
   @XmlElement(name = "AddResources", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addResources;
   @XmlElement(name = "AdministerGlobalExternalApplications", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean administerGlobalExternalApplications;
   @XmlElement(name = "AdministerProjectScheduledServices", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean administerProjectScheduledServices;
   @XmlElement(name = "ApproveResourceTimesheets", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean approveResourceTimesheets;
   @XmlElement(name = "AssignSecureCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean assignSecureCodes;
   @XmlElement(name = "DeleteGlobalActivityCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean deleteGlobalActivityCodes;
   @XmlElement(name = "DeleteGlobalIssueCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean deleteGlobalIssueCodes;
   @XmlElement(name = "DeleteProjectCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean deleteProjectCodes;
   @XmlElement(name = "DeleteResourceCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean deleteResourceCodes;
   @XmlElement(name = "DeleteRoleCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean deleteRoleCodes;
   @XmlElement(name = "DeleteResources", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean deleteResources;
   @XmlElement(name = "AddEditDeleteActivityStepTemplates", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteActivityStepTemplates;
   @XmlElement(name = "AddEditDeleteCategoriesAndOverheadCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteCategoriesAndOverheadCodes;
   @XmlElement(name = "AddEditDeleteCostAccounts", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteCostAccounts;
   @XmlElement(name = "AddEditDeleteCurrencies", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteCurrencies;
   @XmlElement(name = "AddEditDeleteFinancialPeriodDates", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteFinancialPeriodDates;
   @XmlElement(name = "AddEditDeleteFundingSources", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteFundingSources;
   @XmlElement(name = "EditGlobalActivityCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editGlobalActivityCodes;
   @XmlElement(name = "AddEditDeleteGlobalCalendars", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteGlobalCalendars;
   @XmlElement(name = "EditGlobalChangeDefinitions", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editGlobalChangeDefinitions;
   @XmlElement(name = "AddEditDeleteGlobalDashboards", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteGlobalDashboards;
   @XmlElement(name = "EditGlobalIssueCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editGlobalIssueCodes;
   @XmlElement(name = "AddEditDeleteGlobalPortfolios", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteGlobalPortfolios;
   @XmlElement(name = "AddEditDeleteGlobalReports", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteGlobalReports;
   @XmlElement(name = "AddEditDeleteGlobalResourceAndRoleTeams", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteGlobalResourceAndRoleTeams;
   @XmlElement(name = "AddEditDeleteGlobalScenarios", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteGlobalScenarios;
   @XmlElement(name = "EditGlobalTrackingLayouts", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editGlobalTrackingLayouts;
   @XmlElement(name = "AddEditDeleteIssueForms", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteIssueForms;
   @XmlElement(name = "AddEditDeleteMSPTemplates", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteMSPTemplates;
   @XmlElement(name = "AddEditDeleteOBS", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteOBS;
   @XmlElement(name = "EditProjectCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editProjectCodes;
   @XmlElement(name = "EditProjectsFromScorecards", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editProjectsFromScorecards;
   @XmlElement(name = "AddEditDeleteResourceCalendars", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteResourceCalendars;
   @XmlElement(name = "EditResourceCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editResourceCodes;
   @XmlElement(name = "EditRoleCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editRoleCodes;
   @XmlElement(name = "AddEditDeleteResourceCurves", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteResourceCurves;
   @XmlElement(name = "EditResources", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editResources;
   @XmlElement(name = "AddEditDeleteRoles", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteRoles;
   @XmlElement(name = "EditSecureCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editSecureCodes;
   @XmlElement(name = "AddEditDeleteSecurityProfiles", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteSecurityProfiles;
   @XmlElement(name = "AddEditDeleteTimesheetPeriodDates", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteTimesheetPeriodDates;
   @XmlElement(name = "AddEditDeleteUserDefinedFields", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteUserDefinedFields;
   @XmlElement(name = "AddEditDeleteUserInterfaceViews", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteUserInterfaceViews;
   @XmlElement(name = "AddEditDeleteUsers", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteUsers;
   @XmlElement(name = "ImportXERMPPMPXandP3", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean importXERMPPMPXandP3;
   @XmlElement(name = "ImportXML", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean importXML;
   @XmlElement(name = "ImportXLS", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean importXLS;
   @XmlElement(name = "ViewAllGlobalAndProjectDataViaSDK", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean viewAllGlobalAndProjectDataViaSDK;
   @XmlElement(name = "ViewResourceAndRoleCostsAndFinancials", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean viewResourceAndRoleCostsAndFinancials;
   @XmlElement(name = "ViewResourceRoleProficiency", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean viewResourceRoleProficiency;
   @XmlElement(name = "ViewSecureCodes", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean viewSecureCodes;
   @XmlElement(name = "AddEditDeleteRateTypesandUnitsofMeasure", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteRateTypesandUnitsofMeasure;
   @XmlElement(name = "EditApplicationSettings", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean editApplicationSettings;
   @XmlElement(name = "ProvisionUsersfromLDAP", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean provisionUsersfromLDAP;
   @XmlElement(name = "AdministerGlobalScheduledServices", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean administerGlobalScheduledServices;
   @XmlElement(name = "AddEditDeleteLocations", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean addEditDeleteLocations;

   /**
    * Gets the value of the addDeleteSecureCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddDeleteSecureCodes()
   {
      return addDeleteSecureCodes;
   }

   /**
    * Sets the value of the addDeleteSecureCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddDeleteSecureCodes(Boolean value)
   {
      this.addDeleteSecureCodes = value;
   }

   /**
    * Gets the value of the addEditDeleteProjectTemplates property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteProjectTemplates()
   {
      return addEditDeleteProjectTemplates;
   }

   /**
    * Sets the value of the addEditDeleteProjectTemplates property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteProjectTemplates(Boolean value)
   {
      this.addEditDeleteProjectTemplates = value;
   }

   /**
    * Gets the value of the addEditDeleteRiskCategoriesMatricesAndThresholds property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteRiskCategoriesMatricesAndThresholds()
   {
      return addEditDeleteRiskCategoriesMatricesAndThresholds;
   }

   /**
    * Sets the value of the addEditDeleteRiskCategoriesMatricesAndThresholds property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteRiskCategoriesMatricesAndThresholds(Boolean value)
   {
      this.addEditDeleteRiskCategoriesMatricesAndThresholds = value;
   }

   /**
    * Gets the value of the addEditDeleteGlobalActivityAndAssignmentViewsAndFilters property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteGlobalActivityAndAssignmentViewsAndFilters()
   {
      return addEditDeleteGlobalActivityAndAssignmentViewsAndFilters;
   }

   /**
    * Sets the value of the addEditDeleteGlobalActivityAndAssignmentViewsAndFilters property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteGlobalActivityAndAssignmentViewsAndFilters(Boolean value)
   {
      this.addEditDeleteGlobalActivityAndAssignmentViewsAndFilters = value;
   }

   /**
    * Gets the value of the addEditDeleteGlobalProjectWBSPortfolioViewsAndFilters property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteGlobalProjectWBSPortfolioViewsAndFilters()
   {
      return addEditDeleteGlobalProjectWBSPortfolioViewsAndFilters;
   }

   /**
    * Sets the value of the addEditDeleteGlobalProjectWBSPortfolioViewsAndFilters property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteGlobalProjectWBSPortfolioViewsAndFilters(Boolean value)
   {
      this.addEditDeleteGlobalProjectWBSPortfolioViewsAndFilters = value;
   }

   /**
    * Gets the value of the addGlobalActivityCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddGlobalActivityCodes()
   {
      return addGlobalActivityCodes;
   }

   /**
    * Sets the value of the addGlobalActivityCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddGlobalActivityCodes(Boolean value)
   {
      this.addGlobalActivityCodes = value;
   }

   /**
    * Gets the value of the addGlobalIssueCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddGlobalIssueCodes()
   {
      return addGlobalIssueCodes;
   }

   /**
    * Sets the value of the addGlobalIssueCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddGlobalIssueCodes(Boolean value)
   {
      this.addGlobalIssueCodes = value;
   }

   /**
    * Gets the value of the addProjectCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddProjectCodes()
   {
      return addProjectCodes;
   }

   /**
    * Sets the value of the addProjectCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddProjectCodes(Boolean value)
   {
      this.addProjectCodes = value;
   }

   /**
    * Gets the value of the addResourceCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddResourceCodes()
   {
      return addResourceCodes;
   }

   /**
    * Sets the value of the addResourceCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddResourceCodes(Boolean value)
   {
      this.addResourceCodes = value;
   }

   /**
    * Gets the value of the addRoleCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddRoleCodes()
   {
      return addRoleCodes;
   }

   /**
    * Sets the value of the addRoleCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddRoleCodes(Boolean value)
   {
      this.addRoleCodes = value;
   }

   /**
    * Gets the value of the addResources property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddResources()
   {
      return addResources;
   }

   /**
    * Sets the value of the addResources property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddResources(Boolean value)
   {
      this.addResources = value;
   }

   /**
    * Gets the value of the administerGlobalExternalApplications property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAdministerGlobalExternalApplications()
   {
      return administerGlobalExternalApplications;
   }

   /**
    * Sets the value of the administerGlobalExternalApplications property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAdministerGlobalExternalApplications(Boolean value)
   {
      this.administerGlobalExternalApplications = value;
   }

   /**
    * Gets the value of the administerProjectScheduledServices property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAdministerProjectScheduledServices()
   {
      return administerProjectScheduledServices;
   }

   /**
    * Sets the value of the administerProjectScheduledServices property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAdministerProjectScheduledServices(Boolean value)
   {
      this.administerProjectScheduledServices = value;
   }

   /**
    * Gets the value of the approveResourceTimesheets property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isApproveResourceTimesheets()
   {
      return approveResourceTimesheets;
   }

   /**
    * Sets the value of the approveResourceTimesheets property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setApproveResourceTimesheets(Boolean value)
   {
      this.approveResourceTimesheets = value;
   }

   /**
    * Gets the value of the assignSecureCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAssignSecureCodes()
   {
      return assignSecureCodes;
   }

   /**
    * Sets the value of the assignSecureCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAssignSecureCodes(Boolean value)
   {
      this.assignSecureCodes = value;
   }

   /**
    * Gets the value of the deleteGlobalActivityCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isDeleteGlobalActivityCodes()
   {
      return deleteGlobalActivityCodes;
   }

   /**
    * Sets the value of the deleteGlobalActivityCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setDeleteGlobalActivityCodes(Boolean value)
   {
      this.deleteGlobalActivityCodes = value;
   }

   /**
    * Gets the value of the deleteGlobalIssueCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isDeleteGlobalIssueCodes()
   {
      return deleteGlobalIssueCodes;
   }

   /**
    * Sets the value of the deleteGlobalIssueCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setDeleteGlobalIssueCodes(Boolean value)
   {
      this.deleteGlobalIssueCodes = value;
   }

   /**
    * Gets the value of the deleteProjectCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isDeleteProjectCodes()
   {
      return deleteProjectCodes;
   }

   /**
    * Sets the value of the deleteProjectCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setDeleteProjectCodes(Boolean value)
   {
      this.deleteProjectCodes = value;
   }

   /**
    * Gets the value of the deleteResourceCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isDeleteResourceCodes()
   {
      return deleteResourceCodes;
   }

   /**
    * Sets the value of the deleteResourceCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setDeleteResourceCodes(Boolean value)
   {
      this.deleteResourceCodes = value;
   }

   /**
    * Gets the value of the deleteRoleCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isDeleteRoleCodes()
   {
      return deleteRoleCodes;
   }

   /**
    * Sets the value of the deleteRoleCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setDeleteRoleCodes(Boolean value)
   {
      this.deleteRoleCodes = value;
   }

   /**
    * Gets the value of the deleteResources property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isDeleteResources()
   {
      return deleteResources;
   }

   /**
    * Sets the value of the deleteResources property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setDeleteResources(Boolean value)
   {
      this.deleteResources = value;
   }

   /**
    * Gets the value of the addEditDeleteActivityStepTemplates property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteActivityStepTemplates()
   {
      return addEditDeleteActivityStepTemplates;
   }

   /**
    * Sets the value of the addEditDeleteActivityStepTemplates property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteActivityStepTemplates(Boolean value)
   {
      this.addEditDeleteActivityStepTemplates = value;
   }

   /**
    * Gets the value of the addEditDeleteCategoriesAndOverheadCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteCategoriesAndOverheadCodes()
   {
      return addEditDeleteCategoriesAndOverheadCodes;
   }

   /**
    * Sets the value of the addEditDeleteCategoriesAndOverheadCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteCategoriesAndOverheadCodes(Boolean value)
   {
      this.addEditDeleteCategoriesAndOverheadCodes = value;
   }

   /**
    * Gets the value of the addEditDeleteCostAccounts property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteCostAccounts()
   {
      return addEditDeleteCostAccounts;
   }

   /**
    * Sets the value of the addEditDeleteCostAccounts property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteCostAccounts(Boolean value)
   {
      this.addEditDeleteCostAccounts = value;
   }

   /**
    * Gets the value of the addEditDeleteCurrencies property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteCurrencies()
   {
      return addEditDeleteCurrencies;
   }

   /**
    * Sets the value of the addEditDeleteCurrencies property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteCurrencies(Boolean value)
   {
      this.addEditDeleteCurrencies = value;
   }

   /**
    * Gets the value of the addEditDeleteFinancialPeriodDates property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteFinancialPeriodDates()
   {
      return addEditDeleteFinancialPeriodDates;
   }

   /**
    * Sets the value of the addEditDeleteFinancialPeriodDates property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteFinancialPeriodDates(Boolean value)
   {
      this.addEditDeleteFinancialPeriodDates = value;
   }

   /**
    * Gets the value of the addEditDeleteFundingSources property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteFundingSources()
   {
      return addEditDeleteFundingSources;
   }

   /**
    * Sets the value of the addEditDeleteFundingSources property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteFundingSources(Boolean value)
   {
      this.addEditDeleteFundingSources = value;
   }

   /**
    * Gets the value of the editGlobalActivityCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditGlobalActivityCodes()
   {
      return editGlobalActivityCodes;
   }

   /**
    * Sets the value of the editGlobalActivityCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditGlobalActivityCodes(Boolean value)
   {
      this.editGlobalActivityCodes = value;
   }

   /**
    * Gets the value of the addEditDeleteGlobalCalendars property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteGlobalCalendars()
   {
      return addEditDeleteGlobalCalendars;
   }

   /**
    * Sets the value of the addEditDeleteGlobalCalendars property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteGlobalCalendars(Boolean value)
   {
      this.addEditDeleteGlobalCalendars = value;
   }

   /**
    * Gets the value of the editGlobalChangeDefinitions property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditGlobalChangeDefinitions()
   {
      return editGlobalChangeDefinitions;
   }

   /**
    * Sets the value of the editGlobalChangeDefinitions property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditGlobalChangeDefinitions(Boolean value)
   {
      this.editGlobalChangeDefinitions = value;
   }

   /**
    * Gets the value of the addEditDeleteGlobalDashboards property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteGlobalDashboards()
   {
      return addEditDeleteGlobalDashboards;
   }

   /**
    * Sets the value of the addEditDeleteGlobalDashboards property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteGlobalDashboards(Boolean value)
   {
      this.addEditDeleteGlobalDashboards = value;
   }

   /**
    * Gets the value of the editGlobalIssueCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditGlobalIssueCodes()
   {
      return editGlobalIssueCodes;
   }

   /**
    * Sets the value of the editGlobalIssueCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditGlobalIssueCodes(Boolean value)
   {
      this.editGlobalIssueCodes = value;
   }

   /**
    * Gets the value of the addEditDeleteGlobalPortfolios property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteGlobalPortfolios()
   {
      return addEditDeleteGlobalPortfolios;
   }

   /**
    * Sets the value of the addEditDeleteGlobalPortfolios property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteGlobalPortfolios(Boolean value)
   {
      this.addEditDeleteGlobalPortfolios = value;
   }

   /**
    * Gets the value of the addEditDeleteGlobalReports property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteGlobalReports()
   {
      return addEditDeleteGlobalReports;
   }

   /**
    * Sets the value of the addEditDeleteGlobalReports property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteGlobalReports(Boolean value)
   {
      this.addEditDeleteGlobalReports = value;
   }

   /**
    * Gets the value of the addEditDeleteGlobalResourceAndRoleTeams property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteGlobalResourceAndRoleTeams()
   {
      return addEditDeleteGlobalResourceAndRoleTeams;
   }

   /**
    * Sets the value of the addEditDeleteGlobalResourceAndRoleTeams property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteGlobalResourceAndRoleTeams(Boolean value)
   {
      this.addEditDeleteGlobalResourceAndRoleTeams = value;
   }

   /**
    * Gets the value of the addEditDeleteGlobalScenarios property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteGlobalScenarios()
   {
      return addEditDeleteGlobalScenarios;
   }

   /**
    * Sets the value of the addEditDeleteGlobalScenarios property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteGlobalScenarios(Boolean value)
   {
      this.addEditDeleteGlobalScenarios = value;
   }

   /**
    * Gets the value of the editGlobalTrackingLayouts property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditGlobalTrackingLayouts()
   {
      return editGlobalTrackingLayouts;
   }

   /**
    * Sets the value of the editGlobalTrackingLayouts property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditGlobalTrackingLayouts(Boolean value)
   {
      this.editGlobalTrackingLayouts = value;
   }

   /**
    * Gets the value of the addEditDeleteIssueForms property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteIssueForms()
   {
      return addEditDeleteIssueForms;
   }

   /**
    * Sets the value of the addEditDeleteIssueForms property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteIssueForms(Boolean value)
   {
      this.addEditDeleteIssueForms = value;
   }

   /**
    * Gets the value of the addEditDeleteMSPTemplates property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteMSPTemplates()
   {
      return addEditDeleteMSPTemplates;
   }

   /**
    * Sets the value of the addEditDeleteMSPTemplates property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteMSPTemplates(Boolean value)
   {
      this.addEditDeleteMSPTemplates = value;
   }

   /**
    * Gets the value of the addEditDeleteOBS property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteOBS()
   {
      return addEditDeleteOBS;
   }

   /**
    * Sets the value of the addEditDeleteOBS property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteOBS(Boolean value)
   {
      this.addEditDeleteOBS = value;
   }

   /**
    * Gets the value of the editProjectCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditProjectCodes()
   {
      return editProjectCodes;
   }

   /**
    * Sets the value of the editProjectCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditProjectCodes(Boolean value)
   {
      this.editProjectCodes = value;
   }

   /**
    * Gets the value of the editProjectsFromScorecards property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditProjectsFromScorecards()
   {
      return editProjectsFromScorecards;
   }

   /**
    * Sets the value of the editProjectsFromScorecards property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditProjectsFromScorecards(Boolean value)
   {
      this.editProjectsFromScorecards = value;
   }

   /**
    * Gets the value of the addEditDeleteResourceCalendars property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteResourceCalendars()
   {
      return addEditDeleteResourceCalendars;
   }

   /**
    * Sets the value of the addEditDeleteResourceCalendars property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteResourceCalendars(Boolean value)
   {
      this.addEditDeleteResourceCalendars = value;
   }

   /**
    * Gets the value of the editResourceCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditResourceCodes()
   {
      return editResourceCodes;
   }

   /**
    * Sets the value of the editResourceCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditResourceCodes(Boolean value)
   {
      this.editResourceCodes = value;
   }

   /**
    * Gets the value of the editRoleCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditRoleCodes()
   {
      return editRoleCodes;
   }

   /**
    * Sets the value of the editRoleCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditRoleCodes(Boolean value)
   {
      this.editRoleCodes = value;
   }

   /**
    * Gets the value of the addEditDeleteResourceCurves property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteResourceCurves()
   {
      return addEditDeleteResourceCurves;
   }

   /**
    * Sets the value of the addEditDeleteResourceCurves property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteResourceCurves(Boolean value)
   {
      this.addEditDeleteResourceCurves = value;
   }

   /**
    * Gets the value of the editResources property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditResources()
   {
      return editResources;
   }

   /**
    * Sets the value of the editResources property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditResources(Boolean value)
   {
      this.editResources = value;
   }

   /**
    * Gets the value of the addEditDeleteRoles property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteRoles()
   {
      return addEditDeleteRoles;
   }

   /**
    * Sets the value of the addEditDeleteRoles property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteRoles(Boolean value)
   {
      this.addEditDeleteRoles = value;
   }

   /**
    * Gets the value of the editSecureCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditSecureCodes()
   {
      return editSecureCodes;
   }

   /**
    * Sets the value of the editSecureCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditSecureCodes(Boolean value)
   {
      this.editSecureCodes = value;
   }

   /**
    * Gets the value of the addEditDeleteSecurityProfiles property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteSecurityProfiles()
   {
      return addEditDeleteSecurityProfiles;
   }

   /**
    * Sets the value of the addEditDeleteSecurityProfiles property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteSecurityProfiles(Boolean value)
   {
      this.addEditDeleteSecurityProfiles = value;
   }

   /**
    * Gets the value of the addEditDeleteTimesheetPeriodDates property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteTimesheetPeriodDates()
   {
      return addEditDeleteTimesheetPeriodDates;
   }

   /**
    * Sets the value of the addEditDeleteTimesheetPeriodDates property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteTimesheetPeriodDates(Boolean value)
   {
      this.addEditDeleteTimesheetPeriodDates = value;
   }

   /**
    * Gets the value of the addEditDeleteUserDefinedFields property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteUserDefinedFields()
   {
      return addEditDeleteUserDefinedFields;
   }

   /**
    * Sets the value of the addEditDeleteUserDefinedFields property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteUserDefinedFields(Boolean value)
   {
      this.addEditDeleteUserDefinedFields = value;
   }

   /**
    * Gets the value of the addEditDeleteUserInterfaceViews property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteUserInterfaceViews()
   {
      return addEditDeleteUserInterfaceViews;
   }

   /**
    * Sets the value of the addEditDeleteUserInterfaceViews property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteUserInterfaceViews(Boolean value)
   {
      this.addEditDeleteUserInterfaceViews = value;
   }

   /**
    * Gets the value of the addEditDeleteUsers property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteUsers()
   {
      return addEditDeleteUsers;
   }

   /**
    * Sets the value of the addEditDeleteUsers property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteUsers(Boolean value)
   {
      this.addEditDeleteUsers = value;
   }

   /**
    * Gets the value of the importXERMPPMPXandP3 property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isImportXERMPPMPXandP3()
   {
      return importXERMPPMPXandP3;
   }

   /**
    * Sets the value of the importXERMPPMPXandP3 property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setImportXERMPPMPXandP3(Boolean value)
   {
      this.importXERMPPMPXandP3 = value;
   }

   /**
    * Gets the value of the importXML property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isImportXML()
   {
      return importXML;
   }

   /**
    * Sets the value of the importXML property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setImportXML(Boolean value)
   {
      this.importXML = value;
   }

   /**
    * Gets the value of the importXLS property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isImportXLS()
   {
      return importXLS;
   }

   /**
    * Sets the value of the importXLS property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setImportXLS(Boolean value)
   {
      this.importXLS = value;
   }

   /**
    * Gets the value of the viewAllGlobalAndProjectDataViaSDK property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isViewAllGlobalAndProjectDataViaSDK()
   {
      return viewAllGlobalAndProjectDataViaSDK;
   }

   /**
    * Sets the value of the viewAllGlobalAndProjectDataViaSDK property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setViewAllGlobalAndProjectDataViaSDK(Boolean value)
   {
      this.viewAllGlobalAndProjectDataViaSDK = value;
   }

   /**
    * Gets the value of the viewResourceAndRoleCostsAndFinancials property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isViewResourceAndRoleCostsAndFinancials()
   {
      return viewResourceAndRoleCostsAndFinancials;
   }

   /**
    * Sets the value of the viewResourceAndRoleCostsAndFinancials property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setViewResourceAndRoleCostsAndFinancials(Boolean value)
   {
      this.viewResourceAndRoleCostsAndFinancials = value;
   }

   /**
    * Gets the value of the viewResourceRoleProficiency property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isViewResourceRoleProficiency()
   {
      return viewResourceRoleProficiency;
   }

   /**
    * Sets the value of the viewResourceRoleProficiency property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setViewResourceRoleProficiency(Boolean value)
   {
      this.viewResourceRoleProficiency = value;
   }

   /**
    * Gets the value of the viewSecureCodes property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isViewSecureCodes()
   {
      return viewSecureCodes;
   }

   /**
    * Sets the value of the viewSecureCodes property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setViewSecureCodes(Boolean value)
   {
      this.viewSecureCodes = value;
   }

   /**
    * Gets the value of the addEditDeleteRateTypesandUnitsofMeasure property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteRateTypesandUnitsofMeasure()
   {
      return addEditDeleteRateTypesandUnitsofMeasure;
   }

   /**
    * Sets the value of the addEditDeleteRateTypesandUnitsofMeasure property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteRateTypesandUnitsofMeasure(Boolean value)
   {
      this.addEditDeleteRateTypesandUnitsofMeasure = value;
   }

   /**
    * Gets the value of the editApplicationSettings property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isEditApplicationSettings()
   {
      return editApplicationSettings;
   }

   /**
    * Sets the value of the editApplicationSettings property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setEditApplicationSettings(Boolean value)
   {
      this.editApplicationSettings = value;
   }

   /**
    * Gets the value of the provisionUsersfromLDAP property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isProvisionUsersfromLDAP()
   {
      return provisionUsersfromLDAP;
   }

   /**
    * Sets the value of the provisionUsersfromLDAP property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setProvisionUsersfromLDAP(Boolean value)
   {
      this.provisionUsersfromLDAP = value;
   }

   /**
    * Gets the value of the administerGlobalScheduledServices property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAdministerGlobalScheduledServices()
   {
      return administerGlobalScheduledServices;
   }

   /**
    * Sets the value of the administerGlobalScheduledServices property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAdministerGlobalScheduledServices(Boolean value)
   {
      this.administerGlobalScheduledServices = value;
   }

   /**
    * Gets the value of the addEditDeleteLocations property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isAddEditDeleteLocations()
   {
      return addEditDeleteLocations;
   }

   /**
    * Sets the value of the addEditDeleteLocations property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setAddEditDeleteLocations(Boolean value)
   {
      this.addEditDeleteLocations = value;
   }

}
