//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.01.02 at 04:27:10 PM GMT
//

package org.mpxj.primavera.schema;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for ResourceRequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ResourceRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FinishDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="MatchAllCriteria" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RequestedUnits" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="SequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ShowOnlyLaborResources" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ShowOverallocatedResources" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="SortResultsByAvailability" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="UseActivityDates" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ResourceRequestCriterion" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CriterionType"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Primary Role"/&gt;
 *                         &lt;enumeration value="Role"/&gt;
 *                         &lt;enumeration value="Resource"/&gt;
 *                         &lt;enumeration value="Resource Code"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Proficiency" minOccurs="0"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="1 - Master"/&gt;
 *                         &lt;enumeration value="2 - Expert"/&gt;
 *                         &lt;enumeration value="3 - Skilled"/&gt;
 *                         &lt;enumeration value="4 - Proficient"/&gt;
 *                         &lt;enumeration value="5 - Inexperienced"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="ValueObjectId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "ResourceRequestType", propOrder =
{
   "finishDate",
   "matchAllCriteria",
   "name",
   "requestedUnits",
   "sequenceNumber",
   "showOnlyLaborResources",
   "showOverallocatedResources",
   "sortResultsByAvailability",
   "startDate",
   "useActivityDates",
   "resourceRequestCriterion"
}) public class ResourceRequestType
{

   @XmlElement(name = "FinishDate", type = String.class, nillable = true) @XmlJavaTypeAdapter(Adapter4.class) @XmlSchemaType(name = "dateTime") protected LocalDateTime finishDate;
   @XmlElement(name = "MatchAllCriteria", type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean matchAllCriteria;
   @XmlElement(name = "Name") @XmlJavaTypeAdapter(Adapter1.class) protected String name;
   @XmlElement(name = "RequestedUnits", type = String.class, nillable = true) @XmlJavaTypeAdapter(Adapter3.class) @XmlSchemaType(name = "double") protected Double requestedUnits;
   @XmlElement(name = "SequenceNumber") protected Integer sequenceNumber;
   @XmlElement(name = "ShowOnlyLaborResources", type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean showOnlyLaborResources;
   @XmlElement(name = "ShowOverallocatedResources", type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean showOverallocatedResources;
   @XmlElement(name = "SortResultsByAvailability", type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean sortResultsByAvailability;
   @XmlElement(name = "StartDate", type = String.class, nillable = true) @XmlJavaTypeAdapter(Adapter4.class) @XmlSchemaType(name = "dateTime") protected LocalDateTime startDate;
   @XmlElement(name = "UseActivityDates", type = String.class) @XmlJavaTypeAdapter(Adapter2.class) @XmlSchemaType(name = "boolean") protected Boolean useActivityDates;
   @XmlElement(name = "ResourceRequestCriterion") protected List<ResourceRequestType.ResourceRequestCriterion> resourceRequestCriterion;

   /**
    * Gets the value of the finishDate property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public LocalDateTime getFinishDate()
   {
      return finishDate;
   }

   /**
    * Sets the value of the finishDate property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setFinishDate(LocalDateTime value)
   {
      this.finishDate = value;
   }

   /**
    * Gets the value of the matchAllCriteria property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isMatchAllCriteria()
   {
      return matchAllCriteria;
   }

   /**
    * Sets the value of the matchAllCriteria property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setMatchAllCriteria(Boolean value)
   {
      this.matchAllCriteria = value;
   }

   /**
    * Gets the value of the name property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public String getName()
   {
      return name;
   }

   /**
    * Sets the value of the name property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setName(String value)
   {
      this.name = value;
   }

   /**
    * Gets the value of the requestedUnits property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Double getRequestedUnits()
   {
      return requestedUnits;
   }

   /**
    * Sets the value of the requestedUnits property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setRequestedUnits(Double value)
   {
      this.requestedUnits = value;
   }

   /**
    * Gets the value of the sequenceNumber property.
    *
    * @return
    *     possible object is
    *     {@link Integer }
    *
    */
   public Integer getSequenceNumber()
   {
      return sequenceNumber;
   }

   /**
    * Sets the value of the sequenceNumber property.
    *
    * @param value
    *     allowed object is
    *     {@link Integer }
    *
    */
   public void setSequenceNumber(Integer value)
   {
      this.sequenceNumber = value;
   }

   /**
    * Gets the value of the showOnlyLaborResources property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isShowOnlyLaborResources()
   {
      return showOnlyLaborResources;
   }

   /**
    * Sets the value of the showOnlyLaborResources property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setShowOnlyLaborResources(Boolean value)
   {
      this.showOnlyLaborResources = value;
   }

   /**
    * Gets the value of the showOverallocatedResources property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isShowOverallocatedResources()
   {
      return showOverallocatedResources;
   }

   /**
    * Sets the value of the showOverallocatedResources property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setShowOverallocatedResources(Boolean value)
   {
      this.showOverallocatedResources = value;
   }

   /**
    * Gets the value of the sortResultsByAvailability property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isSortResultsByAvailability()
   {
      return sortResultsByAvailability;
   }

   /**
    * Sets the value of the sortResultsByAvailability property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setSortResultsByAvailability(Boolean value)
   {
      this.sortResultsByAvailability = value;
   }

   /**
    * Gets the value of the startDate property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public LocalDateTime getStartDate()
   {
      return startDate;
   }

   /**
    * Sets the value of the startDate property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setStartDate(LocalDateTime value)
   {
      this.startDate = value;
   }

   /**
    * Gets the value of the useActivityDates property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Boolean isUseActivityDates()
   {
      return useActivityDates;
   }

   /**
    * Sets the value of the useActivityDates property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setUseActivityDates(Boolean value)
   {
      this.useActivityDates = value;
   }

   /**
    * Gets the value of the resourceRequestCriterion property.
    *
    * <p>
    * This accessor method returns a reference to the live list,
    * not a snapshot. Therefore any modification you make to the
    * returned list will be present inside the Jakarta XML Binding object.
    * This is why there is not a <CODE>set</CODE> method for the resourceRequestCriterion property.
    *
    * <p>
    * For example, to add a new item, do as follows:
    * <pre>
    *    getResourceRequestCriterion().add(newItem);
    * </pre>
    *
    *
    * <p>
    * Objects of the following type(s) are allowed in the list
    * {@link ResourceRequestType.ResourceRequestCriterion }
    *
    *
    */
   public List<ResourceRequestType.ResourceRequestCriterion> getResourceRequestCriterion()
   {
      if (resourceRequestCriterion == null)
      {
         resourceRequestCriterion = new ArrayList<>();
      }
      return this.resourceRequestCriterion;
   }

   /**
    * <p>Java class for anonymous complex type.
    *
    * <p>The following schema fragment specifies the expected content contained within this class.
    *
    * <pre>
    * &lt;complexType&gt;
    *   &lt;complexContent&gt;
    *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
    *       &lt;sequence&gt;
    *         &lt;element name="CriterionType"&gt;
    *           &lt;simpleType&gt;
    *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
    *               &lt;enumeration value="Primary Role"/&gt;
    *               &lt;enumeration value="Role"/&gt;
    *               &lt;enumeration value="Resource"/&gt;
    *               &lt;enumeration value="Resource Code"/&gt;
    *             &lt;/restriction&gt;
    *           &lt;/simpleType&gt;
    *         &lt;/element&gt;
    *         &lt;element name="Proficiency" minOccurs="0"&gt;
    *           &lt;simpleType&gt;
    *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
    *               &lt;enumeration value="1 - Master"/&gt;
    *               &lt;enumeration value="2 - Expert"/&gt;
    *               &lt;enumeration value="3 - Skilled"/&gt;
    *               &lt;enumeration value="4 - Proficient"/&gt;
    *               &lt;enumeration value="5 - Inexperienced"/&gt;
    *             &lt;/restriction&gt;
    *           &lt;/simpleType&gt;
    *         &lt;/element&gt;
    *         &lt;element name="ValueObjectId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
    *       &lt;/sequence&gt;
    *     &lt;/restriction&gt;
    *   &lt;/complexContent&gt;
    * &lt;/complexType&gt;
    * </pre>
    *
    *
    */
   @XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "", propOrder =
   {
      "criterionType",
      "proficiency",
      "valueObjectId"
   }) public static class ResourceRequestCriterion
   {

      @XmlElement(name = "CriterionType", required = true) @XmlJavaTypeAdapter(Adapter1.class) protected String criterionType;
      @XmlElement(name = "Proficiency") @XmlJavaTypeAdapter(Adapter1.class) protected String proficiency;
      @XmlElement(name = "ValueObjectId") protected int valueObjectId;

      /**
       * Gets the value of the criterionType property.
       *
       * @return
       *     possible object is
       *     {@link String }
       *
       */
      public String getCriterionType()
      {
         return criterionType;
      }

      /**
       * Sets the value of the criterionType property.
       *
       * @param value
       *     allowed object is
       *     {@link String }
       *
       */
      public void setCriterionType(String value)
      {
         this.criterionType = value;
      }

      /**
       * Gets the value of the proficiency property.
       *
       * @return
       *     possible object is
       *     {@link String }
       *
       */
      public String getProficiency()
      {
         return proficiency;
      }

      /**
       * Sets the value of the proficiency property.
       *
       * @param value
       *     allowed object is
       *     {@link String }
       *
       */
      public void setProficiency(String value)
      {
         this.proficiency = value;
      }

      /**
       * Gets the value of the valueObjectId property.
       *
       */
      public int getValueObjectId()
      {
         return valueObjectId;
      }

      /**
       * Sets the value of the valueObjectId property.
       *
       */
      public void setValueObjectId(int value)
      {
         this.valueObjectId = value;
      }

   }

}
