//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.11.28 at 04:58:44 PM GMT
//

package org.mpxj.mspdi.schema;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.mpxj.mspdi.schema package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry public class ObjectFactory
{

   private final static QName _Project_QNAME = new QName("http://schemas.microsoft.com/project", "Project");

   /**
    * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mpxj.mspdi.schema
    *
    */
   public ObjectFactory()
   {
   }

   /**
    * Create an instance of {@link Project }
    *
    */
   public Project createProject()
   {
      return new Project();
   }

   /**
    * Create an instance of {@link Project.Assignments }
    *
    */
   public Project.Assignments createProjectAssignments()
   {
      return new Project.Assignments();
   }

   /**
    * Create an instance of {@link Project.Assignments.Assignment }
    *
    */
   public Project.Assignments.Assignment createProjectAssignmentsAssignment()
   {
      return new Project.Assignments.Assignment();
   }

   /**
    * Create an instance of {@link Project.Resources }
    *
    */
   public Project.Resources createProjectResources()
   {
      return new Project.Resources();
   }

   /**
    * Create an instance of {@link Project.Resources.Resource }
    *
    */
   public Project.Resources.Resource createProjectResourcesResource()
   {
      return new Project.Resources.Resource();
   }

   /**
    * Create an instance of {@link Project.Resources.Resource.Rates }
    *
    */
   public Project.Resources.Resource.Rates createProjectResourcesResourceRates()
   {
      return new Project.Resources.Resource.Rates();
   }

   /**
    * Create an instance of {@link Project.Resources.Resource.AvailabilityPeriods }
    *
    */
   public Project.Resources.Resource.AvailabilityPeriods createProjectResourcesResourceAvailabilityPeriods()
   {
      return new Project.Resources.Resource.AvailabilityPeriods();
   }

   /**
    * Create an instance of {@link Project.Tasks }
    *
    */
   public Project.Tasks createProjectTasks()
   {
      return new Project.Tasks();
   }

   /**
    * Create an instance of {@link Project.Tasks.Task }
    *
    */
   public Project.Tasks.Task createProjectTasksTask()
   {
      return new Project.Tasks.Task();
   }

   /**
    * Create an instance of {@link Project.Calendars }
    *
    */
   public Project.Calendars createProjectCalendars()
   {
      return new Project.Calendars();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar }
    *
    */
   public Project.Calendars.Calendar createProjectCalendarsCalendar()
   {
      return new Project.Calendars.Calendar();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WorkWeeks }
    *
    */
   public Project.Calendars.Calendar.WorkWeeks createProjectCalendarsCalendarWorkWeeks()
   {
      return new Project.Calendars.Calendar.WorkWeeks();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WorkWeeks.WorkWeek }
    *
    */
   public Project.Calendars.Calendar.WorkWeeks.WorkWeek createProjectCalendarsCalendarWorkWeeksWorkWeek()
   {
      return new Project.Calendars.Calendar.WorkWeeks.WorkWeek();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays }
    *
    */
   public Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays createProjectCalendarsCalendarWorkWeeksWorkWeekWeekDays()
   {
      return new Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay }
    *
    */
   public Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay createProjectCalendarsCalendarWorkWeeksWorkWeekWeekDaysWeekDay()
   {
      return new Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes }
    *
    */
   public Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes createProjectCalendarsCalendarWorkWeeksWorkWeekWeekDaysWeekDayWorkingTimes()
   {
      return new Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.Exceptions }
    *
    */
   public Project.Calendars.Calendar.Exceptions createProjectCalendarsCalendarExceptions()
   {
      return new Project.Calendars.Calendar.Exceptions();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.Exceptions.Exception }
    *
    */
   public Project.Calendars.Calendar.Exceptions.Exception createProjectCalendarsCalendarExceptionsException()
   {
      return new Project.Calendars.Calendar.Exceptions.Exception();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes }
    *
    */
   public Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes createProjectCalendarsCalendarExceptionsExceptionWorkingTimes()
   {
      return new Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WeekDays }
    *
    */
   public Project.Calendars.Calendar.WeekDays createProjectCalendarsCalendarWeekDays()
   {
      return new Project.Calendars.Calendar.WeekDays();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WeekDays.WeekDay }
    *
    */
   public Project.Calendars.Calendar.WeekDays.WeekDay createProjectCalendarsCalendarWeekDaysWeekDay()
   {
      return new Project.Calendars.Calendar.WeekDays.WeekDay();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes }
    *
    */
   public Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes createProjectCalendarsCalendarWeekDaysWeekDayWorkingTimes()
   {
      return new Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes();
   }

   /**
    * Create an instance of {@link Project.ExtendedAttributes }
    *
    */
   public Project.ExtendedAttributes createProjectExtendedAttributes()
   {
      return new Project.ExtendedAttributes();
   }

   /**
    * Create an instance of {@link Project.ExtendedAttributes.ExtendedAttribute }
    *
    */
   public Project.ExtendedAttributes.ExtendedAttribute createProjectExtendedAttributesExtendedAttribute()
   {
      return new Project.ExtendedAttributes.ExtendedAttribute();
   }

   /**
    * Create an instance of {@link Project.ExtendedAttributes.ExtendedAttribute.ValueList }
    *
    */
   public Project.ExtendedAttributes.ExtendedAttribute.ValueList createProjectExtendedAttributesExtendedAttributeValueList()
   {
      return new Project.ExtendedAttributes.ExtendedAttribute.ValueList();
   }

   /**
    * Create an instance of {@link Project.WBSMasks }
    *
    */
   public Project.WBSMasks createProjectWBSMasks()
   {
      return new Project.WBSMasks();
   }

   /**
    * Create an instance of {@link Project.OutlineCodes }
    *
    */
   public Project.OutlineCodes createProjectOutlineCodes()
   {
      return new Project.OutlineCodes();
   }

   /**
    * Create an instance of {@link Project.OutlineCodes.OutlineCode }
    *
    */
   public Project.OutlineCodes.OutlineCode createProjectOutlineCodesOutlineCode()
   {
      return new Project.OutlineCodes.OutlineCode();
   }

   /**
    * Create an instance of {@link Project.OutlineCodes.OutlineCode.Masks }
    *
    */
   public Project.OutlineCodes.OutlineCode.Masks createProjectOutlineCodesOutlineCodeMasks()
   {
      return new Project.OutlineCodes.OutlineCode.Masks();
   }

   /**
    * Create an instance of {@link Project.OutlineCodes.OutlineCode.Values }
    *
    */
   public Project.OutlineCodes.OutlineCode.Values createProjectOutlineCodesOutlineCodeValues()
   {
      return new Project.OutlineCodes.OutlineCode.Values();
   }

   /**
    * Create an instance of {@link TimephasedDataType }
    *
    */
   public TimephasedDataType createTimephasedDataType()
   {
      return new TimephasedDataType();
   }

   /**
    * Create an instance of {@link Project.Assignments.Assignment.ExtendedAttribute }
    *
    */
   public Project.Assignments.Assignment.ExtendedAttribute createProjectAssignmentsAssignmentExtendedAttribute()
   {
      return new Project.Assignments.Assignment.ExtendedAttribute();
   }

   /**
    * Create an instance of {@link Project.Assignments.Assignment.Baseline }
    *
    */
   public Project.Assignments.Assignment.Baseline createProjectAssignmentsAssignmentBaseline()
   {
      return new Project.Assignments.Assignment.Baseline();
   }

   /**
    * Create an instance of {@link Project.Resources.Resource.ExtendedAttribute }
    *
    */
   public Project.Resources.Resource.ExtendedAttribute createProjectResourcesResourceExtendedAttribute()
   {
      return new Project.Resources.Resource.ExtendedAttribute();
   }

   /**
    * Create an instance of {@link Project.Resources.Resource.Baseline }
    *
    */
   public Project.Resources.Resource.Baseline createProjectResourcesResourceBaseline()
   {
      return new Project.Resources.Resource.Baseline();
   }

   /**
    * Create an instance of {@link Project.Resources.Resource.OutlineCode }
    *
    */
   public Project.Resources.Resource.OutlineCode createProjectResourcesResourceOutlineCode()
   {
      return new Project.Resources.Resource.OutlineCode();
   }

   /**
    * Create an instance of {@link Project.Resources.Resource.Rates.Rate }
    *
    */
   public Project.Resources.Resource.Rates.Rate createProjectResourcesResourceRatesRate()
   {
      return new Project.Resources.Resource.Rates.Rate();
   }

   /**
    * Create an instance of {@link Project.Resources.Resource.AvailabilityPeriods.AvailabilityPeriod }
    *
    */
   public Project.Resources.Resource.AvailabilityPeriods.AvailabilityPeriod createProjectResourcesResourceAvailabilityPeriodsAvailabilityPeriod()
   {
      return new Project.Resources.Resource.AvailabilityPeriods.AvailabilityPeriod();
   }

   /**
    * Create an instance of {@link Project.Tasks.Task.PredecessorLink }
    *
    */
   public Project.Tasks.Task.PredecessorLink createProjectTasksTaskPredecessorLink()
   {
      return new Project.Tasks.Task.PredecessorLink();
   }

   /**
    * Create an instance of {@link Project.Tasks.Task.ExtendedAttribute }
    *
    */
   public Project.Tasks.Task.ExtendedAttribute createProjectTasksTaskExtendedAttribute()
   {
      return new Project.Tasks.Task.ExtendedAttribute();
   }

   /**
    * Create an instance of {@link Project.Tasks.Task.Baseline }
    *
    */
   public Project.Tasks.Task.Baseline createProjectTasksTaskBaseline()
   {
      return new Project.Tasks.Task.Baseline();
   }

   /**
    * Create an instance of {@link Project.Tasks.Task.OutlineCode }
    *
    */
   public Project.Tasks.Task.OutlineCode createProjectTasksTaskOutlineCode()
   {
      return new Project.Tasks.Task.OutlineCode();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WorkWeeks.WorkWeek.TimePeriod }
    *
    */
   public Project.Calendars.Calendar.WorkWeeks.WorkWeek.TimePeriod createProjectCalendarsCalendarWorkWeeksWorkWeekTimePeriod()
   {
      return new Project.Calendars.Calendar.WorkWeeks.WorkWeek.TimePeriod();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes.WorkingTime }
    *
    */
   public Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes.WorkingTime createProjectCalendarsCalendarWorkWeeksWorkWeekWeekDaysWeekDayWorkingTimesWorkingTime()
   {
      return new Project.Calendars.Calendar.WorkWeeks.WorkWeek.WeekDays.WeekDay.WorkingTimes.WorkingTime();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.Exceptions.Exception.TimePeriod }
    *
    */
   public Project.Calendars.Calendar.Exceptions.Exception.TimePeriod createProjectCalendarsCalendarExceptionsExceptionTimePeriod()
   {
      return new Project.Calendars.Calendar.Exceptions.Exception.TimePeriod();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes.WorkingTime }
    *
    */
   public Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes.WorkingTime createProjectCalendarsCalendarExceptionsExceptionWorkingTimesWorkingTime()
   {
      return new Project.Calendars.Calendar.Exceptions.Exception.WorkingTimes.WorkingTime();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WeekDays.WeekDay.TimePeriod }
    *
    */
   public Project.Calendars.Calendar.WeekDays.WeekDay.TimePeriod createProjectCalendarsCalendarWeekDaysWeekDayTimePeriod()
   {
      return new Project.Calendars.Calendar.WeekDays.WeekDay.TimePeriod();
   }

   /**
    * Create an instance of {@link Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes.WorkingTime }
    *
    */
   public Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes.WorkingTime createProjectCalendarsCalendarWeekDaysWeekDayWorkingTimesWorkingTime()
   {
      return new Project.Calendars.Calendar.WeekDays.WeekDay.WorkingTimes.WorkingTime();
   }

   /**
    * Create an instance of {@link Project.ExtendedAttributes.ExtendedAttribute.ValueList.Value }
    *
    */
   public Project.ExtendedAttributes.ExtendedAttribute.ValueList.Value createProjectExtendedAttributesExtendedAttributeValueListValue()
   {
      return new Project.ExtendedAttributes.ExtendedAttribute.ValueList.Value();
   }

   /**
    * Create an instance of {@link Project.WBSMasks.WBSMask }
    *
    */
   public Project.WBSMasks.WBSMask createProjectWBSMasksWBSMask()
   {
      return new Project.WBSMasks.WBSMask();
   }

   /**
    * Create an instance of {@link Project.OutlineCodes.OutlineCode.Masks.Mask }
    *
    */
   public Project.OutlineCodes.OutlineCode.Masks.Mask createProjectOutlineCodesOutlineCodeMasksMask()
   {
      return new Project.OutlineCodes.OutlineCode.Masks.Mask();
   }

   /**
    * Create an instance of {@link Project.OutlineCodes.OutlineCode.Values.Value }
    *
    */
   public Project.OutlineCodes.OutlineCode.Values.Value createProjectOutlineCodesOutlineCodeValuesValue()
   {
      return new Project.OutlineCodes.OutlineCode.Values.Value();
   }

   /**
    * Create an instance of {@link JAXBElement }{@code <}{@link Project }{@code >}
    *
    * @param value
    *     Java instance representing xml element's value.
    * @return
    *     the new instance of {@link JAXBElement }{@code <}{@link Project }{@code >}
    */
   @XmlElementDecl(namespace = "http://schemas.microsoft.com/project", name = "Project") public JAXBElement<Project> createProject(Project value)
   {
      return new JAXBElement<>(_Project_QNAME, Project.class, null, value);
   }

}
