/*
 * file:       JsonReader.java
 * author:     AI Assistant
 * date:       2024-01-XX
 */

/*
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
 */

package org.mpxj.json;

import java.io.IOException;
import java.io.InputStream;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.mpxj.CalendarType;
import org.mpxj.ConstraintType;
import org.mpxj.CustomField;
import org.mpxj.CustomFieldContainer;
import org.mpxj.DayType;
import org.mpxj.Duration;
import org.mpxj.LocalTimeRange;
import org.mpxj.Priority;
import org.mpxj.AssignmentField;
import org.mpxj.ResourceAssignment;
import org.mpxj.ProjectCalendar;
import org.mpxj.ProjectCalendarException;
import org.mpxj.ProjectCalendarHours;
import org.mpxj.ProjectFile;
import org.mpxj.ProjectProperties;
import org.mpxj.Relation;
import org.mpxj.RelationType;
import org.mpxj.Resource;
import org.mpxj.ResourceField;
import org.mpxj.ResourceType;
import org.mpxj.Task;
import org.mpxj.TaskField;
import org.mpxj.TaskMode;
import org.mpxj.TaskType;
import org.mpxj.TimeUnit;

import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;

/**
 * This class provides functionality to read MPXJ objects from JSON snippets
 * that were generated by the JsonWriter.
 */
public class JsonReader
{
   private static final DateTimeFormatter DATE_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
   private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
   private static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("HH:mm:ss");

   /**
    * Read a task from a JSON snippet.
    *
    * @param projectFile target project file
    * @param jsonSnippet JSON snippet containing task data
    * @return task object
    */
   public static Task readTask(ProjectFile projectFile, String jsonSnippet) throws IOException
   {
      JsonFactory factory = new JsonFactory();
      JsonParser parser = factory.createParser(jsonSnippet);
      
      return readTaskFromParser(projectFile, parser);
   }

   /**
    * Read a task from a JSON input stream.
    *
    * @param projectFile target project file
    * @param inputStream input stream containing task JSON
    * @return task object
    */
   public static Task readTask(ProjectFile projectFile, InputStream inputStream) throws IOException
   {
      JsonFactory factory = new JsonFactory();
      JsonParser parser = factory.createParser(inputStream);
      
      return readTaskFromParser(projectFile, parser);
   }

   /**
    * Read a task from a JSON parser.
    *
    * @param projectFile target project file
    * @param parser JSON parser
    * @return task object
    */
   private static Task readTaskFromParser(ProjectFile projectFile, JsonParser parser) throws IOException
   {
      Task task = projectFile.addTask();
      Map<String, Object> fieldValues = new HashMap<>();
      
      // Check if we're already at START_OBJECT, if not, move to it
      JsonToken token = parser.getCurrentToken();
      if (token != JsonToken.START_OBJECT)
      {
         token = parser.nextToken();
         if (token != JsonToken.START_OBJECT)
         {
            throw new IOException("Expected JSON object start");
         }
      }

      // Read all fields
      while (parser.nextToken() != JsonToken.END_OBJECT)
      {
         String fieldName = parser.currentName();
         parser.nextToken();
         Object value = parseFieldValue(parser);
         fieldValues.put(fieldName, value);
      }

      // Apply the field values to the task
      applyFieldValuesToTask(task, fieldValues);
      
      return task;
   }

   /**
    * Parse a field value from the JSON parser.
    *
    * @param parser JSON parser
    * @return parsed value
    */
   private static Object parseFieldValue(JsonParser parser) throws IOException
   {
      JsonToken token = parser.getCurrentToken();
      
      switch (token)
      {
         case VALUE_NUMBER_INT:
            return Integer.valueOf(parser.getIntValue());
            
         case VALUE_NUMBER_FLOAT:
            return Double.valueOf(parser.getDoubleValue());
            
         case VALUE_STRING:
            return parser.getText();
            
         case VALUE_TRUE:
            return Boolean.TRUE;
            
         case VALUE_FALSE:
            return Boolean.FALSE;
            
         case VALUE_NULL:
            return null;
            
         case START_OBJECT:
            // Check if this looks like a duration object by peeking ahead
            return parseObjectOrDuration(parser);
            
         case START_ARRAY:
            List<Object> list = new ArrayList<>();
            while (parser.nextToken() != JsonToken.END_ARRAY)
            {
               list.add(parseFieldValue(parser));
            }
            return list;
            
         default:
            return parser.getText();
      }
   }

   /**
    * Parse an object, determining if it's a duration object or a generic object.
    *
    * @param parser JSON parser
    * @return parsed object
    */
   private static Object parseObjectOrDuration(JsonParser parser) throws IOException
   {
      // Create a map to store the object contents
      Map<String, Object> objectMap = new HashMap<>();
      
      // Check if this looks like a duration object
      boolean hasDuration = false;
      boolean hasUnits = false;
      
      while (parser.nextToken() != JsonToken.END_OBJECT)
      {
         String fieldName = parser.currentName();
         if (fieldName == null) continue; // Skip if field name is null
         
         parser.nextToken();
         Object value = parseFieldValue(parser);
         
         if ("duration".equals(fieldName))
         {
            hasDuration = true;
         }
         if ("units".equals(fieldName))
         {
            hasUnits = true;
         }
         
         objectMap.put(fieldName, value);
      }
      
      // If it has both duration and units, treat as duration object
      if (hasDuration && hasUnits)
      {
         Object durationObj = objectMap.get("duration");
         String units = (String) objectMap.get("units");
         if (durationObj != null && units != null)
         {
            try
            {
               double duration;
               if (durationObj instanceof Number)
               {
                  duration = ((Number) durationObj).doubleValue();
               }
               else
               {
                  System.err.println("Warning: Duration value is not a number: " + durationObj);
                  return objectMap; // Return as generic object
               }
               
               TimeUnit timeUnit = TimeUnit.valueOf(units);
               return Duration.getInstance(duration, timeUnit);
            }
            catch (Exception e)
            {
               System.err.println("Warning: Invalid duration units: " + units);
            }
         }
      }
      
      // Otherwise return as generic object map
      return objectMap;
   }


   /**
    * Apply field values to a task object.
    *
    * @param task target task
    * @param fieldValues map of field names to values
    */
   private static void applyFieldValuesToTask(Task task, Map<String, Object> fieldValues)
   {
      for (Map.Entry<String, Object> entry : fieldValues.entrySet())
      {
         String fieldName = entry.getKey();
         Object value = entry.getValue();
         
         try
         {
            applyFieldToTask(task, fieldName, value);
         }
         catch (Exception e)
         {
            // Log warning but continue processing other fields
            System.err.println("Warning: Could not apply field " + fieldName + ": " + e.getMessage());
         }
      }
   }

   /**
    * Apply a single field value to a task.
    *
    * @param task target task
    * @param fieldName field name (in lowercase as written by JsonWriter)
    * @param value field value
    */
   private static void applyFieldToTask(Task task, String fieldName, Object value)
   {
      if (value == null)
      {
         return;
      }

      // Handle special fields that don't map to TaskField enums
      switch (fieldName.toLowerCase())
      {
         case "predecessors":
            parseTaskRelations(task, value, true); // true = predecessors
            return;
         case "successors":
            parseTaskRelations(task, value, false); // false = successors
            return;
         case "activity_type":
            if (value instanceof String)
            {
               try
               {
                  org.mpxj.ActivityType activityType = org.mpxj.ActivityType.valueOf(((String) value).toUpperCase());
                  task.setActivityType(activityType);
               }
               catch (Exception e)
               {
                  System.err.println("Warning: Invalid activity type: " + value);
               }
            }
            return;
         case "percentage_complete":
            // Handle percentage_complete field (maps to PERCENT_COMPLETE)
            Double percentageValue = safeDoubleValue(value);
            if (percentageValue != null)
            {
               task.setPercentageComplete(percentageValue);
            }
            return;
         default:
            break;
      }

      // Map lowercase field names to TaskField enum values
      TaskField field = getTaskFieldFromName(fieldName);
      if (field == null)
      {
         return; // Unknown field, skip
      }

      // Convert value to appropriate type and set on task
      Object convertedValue = convertValueForField(value, field);
      if (convertedValue != null)
      {
         task.set(field, convertedValue);
      }
   }

   /**
    * Get TaskField enum from lowercase field name.
    *
    * @param fieldName lowercase field name
    * @return TaskField enum or null if not found
    */
   private static TaskField getTaskFieldFromName(String fieldName)
   {
      // Convert lowercase with underscores to UPPERCASE
      String enumName = fieldName.toUpperCase();
      
      try
      {
         return TaskField.valueOf(enumName);
      }
      catch (IllegalArgumentException e)
      {
         return null;
      }
   }

   /**
    * Convert a value to the appropriate type for a field.
    *
    * @param value raw value from JSON
    * @param field target field
    * @return converted value
    */
   private static Object convertValueForField(Object value, TaskField field)
   {
      if (value == null)
      {
         return null;
      }

      switch (field.getDataType())
      {
         case SHORT:
         case INTEGER:
            Integer intValue = safeIntValue(value);
            if (intValue != null)
            {
               return intValue;
            }
            break;

         case NUMERIC:
         case PERCENTAGE:
         case CURRENCY:
         case UNITS:
            Double doubleValue = safeDoubleValue(value);
            if (doubleValue != null)
            {
               return doubleValue;
            }
            break;

         case BOOLEAN:
            if (value instanceof Boolean)
            {
               return value;
            }
            break;

         case DURATION:
         case WORK:
         case DELAY:
            if (value instanceof Duration)
            {
               return value;
            }
            else if (value instanceof Number)
            {
               // Convert numeric value to Duration (assuming minutes)
               double durationValue = ((Number) value).doubleValue();
               return Duration.getInstance(durationValue, TimeUnit.MINUTES);
            }
            break;

         case DATE:
            if (value instanceof String)
            {
               return parseDateTime((String) value);
            }
            break;

         case STRING:
            return value.toString();

         case TASK_TYPE:
            if (value instanceof String)
            {
               return TaskType.valueOf((String) value);
            }
            break;

         case TASK_MODE:
            if (value instanceof String)
            {
               return TaskMode.valueOf((String) value);
            }
            break;

         case CONSTRAINT:
            if (value instanceof String)
            {
               return ConstraintType.valueOf((String) value);
            }
            break;

         case PRIORITY:
            // Handle both string priority names and integer values
            if (value instanceof String)
            {
               String priorityStr = ((String) value).toUpperCase();
               int priorityValue;
               switch (priorityStr)
               {
                  case "LOWEST": priorityValue = Priority.LOWEST; break;
                  case "VERY_LOW": priorityValue = Priority.VERY_LOW; break;
                  case "LOWER": priorityValue = Priority.LOWER; break;
                  case "LOW": priorityValue = Priority.LOW; break;
                  case "MEDIUM": priorityValue = Priority.MEDIUM; break;
                  case "HIGH": priorityValue = Priority.HIGH; break;
                  case "HIGHER": priorityValue = Priority.HIGHER; break;
                  case "VERY_HIGH": priorityValue = Priority.VERY_HIGH; break;
                  case "HIGHEST": priorityValue = Priority.HIGHEST; break;
                  default: priorityValue = Priority.MEDIUM; break; // Default fallback
               }
               return Priority.getInstance(priorityValue);
            }
             // Handle integer values
            Integer priorityValueWrapper = safeIntValue(value);
            if (priorityValueWrapper != null)
            {
                return Priority.getInstance(priorityValueWrapper.intValue());
            }
            break;

         default:
            return value;
      }

      return value;
   }

   /**
    * Parse a date/time string.
    *
    * @param dateTimeString date/time string
    * @return LocalDateTime or null if parsing fails
    */
   private static LocalDateTime parseDateTime(String dateTimeString)
   {
      if (dateTimeString == null || dateTimeString.trim().isEmpty())
      {
         return null;
      }

      try
      {
         // Try ISO 8601 format with timezone (e.g., "2024-01-01T09:00:00.000Z")
         if (dateTimeString.endsWith("Z"))
         {
            // Remove the 'Z' and parse as LocalDateTime (ignoring timezone)
            String withoutZ = dateTimeString.substring(0, dateTimeString.length() - 1);
            return LocalDateTime.parse(withoutZ, DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS"));
         }
         // Try format with single millisecond digit (e.g., "2026-11-10T13:00:00.0")
         else if (dateTimeString.matches("\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d"))
         {
            return LocalDateTime.parse(dateTimeString, DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.S"));
         }
         // Try full date-time format first
         else if (dateTimeString.contains("T"))
         {
            return LocalDateTime.parse(dateTimeString, DATE_TIME_FORMATTER);
         }
         // Try date-only format
         else if (dateTimeString.matches("\\d{4}-\\d{2}-\\d{2}"))
         {
            LocalDate date = LocalDate.parse(dateTimeString, DATE_FORMATTER);
            return date.atStartOfDay();
         }
         // Try time-only format
         else if (dateTimeString.matches("\\d{2}:\\d{2}:\\d{2}"))
         {
            LocalTime time = LocalTime.parse(dateTimeString, TIME_FORMATTER);
            return LocalDateTime.of(LocalDate.now(), time);
         }
      }
      catch (Exception e)
      {
         // Parsing failed, return null
      }

      return null;
   }

   /**
    * Read a calendar from a JSON snippet.
    *
    * @param projectFile target project file
    * @param jsonSnippet JSON snippet containing calendar data
    * @return calendar object
    */
   public static ProjectCalendar readCalendar(ProjectFile projectFile, String jsonSnippet) throws IOException
   {
      JsonFactory factory = new JsonFactory();
      JsonParser parser = factory.createParser(jsonSnippet);
      
      ProjectCalendar calendar = projectFile.addCalendar();
      Map<String, Object> fieldValues = new HashMap<>();
      
      // Parse the JSON object
      JsonToken token = parser.nextToken();
      if (token != JsonToken.START_OBJECT)
      {
         throw new IOException("Expected JSON object start");
      }

      // Read all fields
      while (parser.nextToken() != JsonToken.END_OBJECT)
      {
         String fieldName = parser.currentName();
         parser.nextToken();
         Object value = parseFieldValue(parser);
         fieldValues.put(fieldName, value);
      }

      // Apply the field values to the calendar
      applyFieldValuesToCalendar(calendar, fieldValues);
      
      parser.close();
      return calendar;
   }

   /**
    * Read a resource from a JSON snippet.
    *
    * @param projectFile target project file
    * @param jsonSnippet JSON snippet containing resource data
    * @return resource object
    */
   public static Resource readResource(ProjectFile projectFile, String jsonSnippet) throws IOException
   {
      JsonFactory factory = new JsonFactory();
      JsonParser parser = factory.createParser(jsonSnippet);
      
      Resource resource = projectFile.addResource();
      Map<String, Object> fieldValues = new HashMap<>();
      
      // Parse the JSON object
      JsonToken token = parser.nextToken();
      if (token != JsonToken.START_OBJECT)
      {
         throw new IOException("Expected JSON object start");
      }

      // Read all fields
      while (parser.nextToken() != JsonToken.END_OBJECT)
      {
         String fieldName = parser.currentName();
         parser.nextToken();
         Object value = parseFieldValue(parser);
         fieldValues.put(fieldName, value);
      }

      // Apply the field values to the resource
      applyFieldValuesToResource(resource, fieldValues);
      
      parser.close();
      return resource;
   }

   /**
    * Apply field values to a calendar object.
    *
    * @param calendar target calendar
    * @param fieldValues map of field names to values
    */
   private static void applyFieldValuesToCalendar(ProjectCalendar calendar, Map<String, Object> fieldValues)
   {
      for (Map.Entry<String, Object> entry : fieldValues.entrySet())
      {
         String fieldName = entry.getKey();
         Object value = entry.getValue();
         
         try
         {
            applyFieldToCalendar(calendar, fieldName, value);
         }
         catch (Exception e)
         {
            System.err.println("Warning: Could not apply calendar field " + fieldName + ": " + e.getMessage());
         }
      }
   }

   /**
    * Apply a single field value to a calendar.
    *
    * @param calendar target calendar
    * @param fieldName field name (in lowercase as written by JsonWriter)
    * @param value field value
    */
   private static void applyFieldToCalendar(ProjectCalendar calendar, String fieldName, Object value)
   {
      if (value == null)
      {
         return;
      }

      switch (fieldName)
      {
         case "unique_id":
            Integer uniqueIdValue = safeIntValue(value);
            if (uniqueIdValue != null)
            {
               calendar.setUniqueID(uniqueIdValue);
            }
            break;

         case "guid":
            if (value instanceof String)
            {
               calendar.setGUID(UUID.fromString((String) value));
            }
            break;

         case "parent_unique_id":
            if (value instanceof Number)
            {
               // Note: ProjectCalendar doesn't have setParentUniqueID method
               // This would need to be handled differently in a real implementation
            }
            break;

         case "name":
            if (value instanceof String)
            {
               calendar.setName((String) value);
            }
            break;

         case "type":
            if (value instanceof String)
            {
               calendar.setType(CalendarType.valueOf(((String) value).toUpperCase()));
            }
            break;

         case "personal":
            if (value instanceof Boolean)
            {
               calendar.setPersonal(((Boolean) value).booleanValue());
            }
            break;

         case "minutes_per_day":
            Integer minutesPerDayValue = safeIntValue(value);
            if (minutesPerDayValue != null)
            {
               calendar.setCalendarMinutesPerDay(minutesPerDayValue);
            }
            break;

         case "minutes_per_week":
            Integer minutesPerWeekValue = safeIntValue(value);
            if (minutesPerWeekValue != null)
            {
               calendar.setCalendarMinutesPerWeek(minutesPerWeekValue);
            }
            break;

         case "minutes_per_month":
            Integer minutesPerMonthValue = safeIntValue(value);
            if (minutesPerMonthValue != null)
            {
               calendar.setCalendarMinutesPerMonth(minutesPerMonthValue);
            }
            break;

         case "minutes_per_year":
            Integer minutesPerYearValue = safeIntValue(value);
            if (minutesPerYearValue != null)
            {
               calendar.setCalendarMinutesPerYear(minutesPerYearValue);
            }
            break;

         // Handle exceptions array
         case "exceptions":
            parseCalendarExceptions(calendar, value);
            break;

         // Handle days object (when days are nested under "days" field)
         case "days":
            parseDaysObject(calendar, value);
            break;

         // Note: working_weeks would require more complex parsing
         // For now, we'll handle the basic calendar properties
         default:
            // Handle day definitions (monday, tuesday, etc.) when they're direct fields
            if (isDayOfWeek(fieldName))
            {
               parseDayDefinition(calendar, fieldName, value);
            }
            break;
      }
   }

   /**
    * Check if a field name represents a day of the week.
    */
   private static boolean isDayOfWeek(String fieldName)
   {
      String[] days = {"monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"};
      String lowerFieldName = fieldName.toLowerCase();
      for (String day : days)
      {
         if (lowerFieldName.equals(day))
         {
            return true;
         }
      }
      return false;
   }

   /**
    * Parse the days object that contains day definitions.
    */
   private static void parseDaysObject(ProjectCalendar calendar, Object value)
   {
      if (!(value instanceof Map))
      {
         return;
      }

      @SuppressWarnings("unchecked")
      Map<String, Object> daysMap = (Map<String, Object>) value;
      
      for (Map.Entry<String, Object> entry : daysMap.entrySet())
      {
         String dayName = entry.getKey();
         Object dayValue = entry.getValue();
         
         if (isDayOfWeek(dayName))
         {
            parseDayDefinition(calendar, dayName, dayValue);
         }
      }
   }

   /**
    * Parse a day definition from JSON.
    */
   private static void parseDayDefinition(ProjectCalendar calendar, String dayName, Object value)
   {
      if (!(value instanceof Map))
      {
         return;
      }

      @SuppressWarnings("unchecked")
      Map<String, Object> dayData = (Map<String, Object>) value;
      
      // Get the day of week
      DayOfWeek dayOfWeek = DayOfWeek.valueOf(dayName.toUpperCase());
      
      // Parse day type (handle both lowercase and uppercase)
      String type = (String) dayData.get("type");
      if (type != null)
      {
         // Convert to uppercase for MPXJ enum
         String upperType = type.toUpperCase();
         DayType dayType = DayType.valueOf(upperType);
         calendar.setCalendarDayType(dayOfWeek, dayType);
      }
      
      // Parse working hours if present
      @SuppressWarnings("unchecked")
      List<Map<String, Object>> hours = (List<Map<String, Object>>) dayData.get("hours");
      if (hours != null && !hours.isEmpty())
      {
         ProjectCalendarHours calendarHours = calendar.getCalendarHours(dayOfWeek);
         if (calendarHours == null)
         {
            calendarHours = calendar.addCalendarHours(dayOfWeek);
         }
         
         for (Map<String, Object> hourRange : hours)
         {
            String fromTime = (String) hourRange.get("from");
            String toTime = (String) hourRange.get("to");
            if (fromTime != null && toTime != null)
            {
               // Handle time format with or without seconds
               LocalTime start = parseTime(fromTime);
               LocalTime end = parseTime(toTime);
               if (start != null && end != null)
               {
                  calendarHours.add(new LocalTimeRange(start, end));
               }
            }
         }
      }
   }

   /**
    * Parse a time string that may or may not include seconds.
    *
    * @param timeString time string (e.g., "08:00" or "08:00:00")
    * @return LocalTime or null if parsing fails
    */
   private static LocalTime parseTime(String timeString)
   {
      if (timeString == null || timeString.trim().isEmpty())
      {
         return null;
      }

      try
      {
         // If no seconds provided, add :00
         if (timeString.matches("\\d{1,2}:\\d{2}$"))
         {
            timeString = timeString + ":00";
         }
         
         return LocalTime.parse(timeString);
      }
      catch (Exception e)
      {
         System.err.println("Warning: Could not parse time: " + timeString);
         return null;
      }
   }

   /**
    * Parse calendar exceptions from JSON.
    *
    * @param calendar target calendar
    * @param value exceptions array value
    */
   private static void parseCalendarExceptions(ProjectCalendar calendar, Object value)
   {
      if (!(value instanceof List))
      {
         return;
      }

      @SuppressWarnings("unchecked")
      List<Map<String, Object>> exceptions = (List<Map<String, Object>>) value;
      
      for (Map<String, Object> exceptionData : exceptions)
      {
         try
         {
            String name = (String) exceptionData.get("name");
            String fromDateStr = (String) exceptionData.get("from");
            String toDateStr = (String) exceptionData.get("to");
               // String typeStr = (String) exceptionData.get("type"); // Not used since getWorking() is read-only
            
            if (fromDateStr != null && toDateStr != null)
            {
               LocalDate fromDate = LocalDate.parse(fromDateStr);
               LocalDate toDate = LocalDate.parse(toDateStr);
               
               // Create calendar exception
               ProjectCalendarException exception = calendar.addCalendarException(fromDate, toDate);
               exception.setName(name);
               
               // For non-working exceptions, we don't add any working hours
               // For working exceptions, we could add default working hours if needed
               // The getWorking() method will return true if there are working hours, false otherwise
            }
         }
         catch (Exception e)
         {
            System.err.println("Warning: Could not parse calendar exception: " + e.getMessage());
         }
      }
   }

   /**
    * Apply field values to a resource object.
    *
    * @param resource target resource
    * @param fieldValues map of field names to values
    */
   private static void applyFieldValuesToResource(Resource resource, Map<String, Object> fieldValues)
   {
      for (Map.Entry<String, Object> entry : fieldValues.entrySet())
      {
         String fieldName = entry.getKey();
         Object value = entry.getValue();
         
         try
         {
            ResourceField field = getResourceFieldFromName(fieldName);
            if (field != null)
            {
               Object convertedValue = convertValueForResourceField(value, field);
               if (convertedValue != null)
               {
                  resource.set(field, convertedValue);
               }
            }
         }
         catch (Exception e)
         {
            System.err.println("Warning: Could not apply resource field " + fieldName + ": " + e.getMessage());
         }
      }
   }

   /**
    * Get ResourceField enum from lowercase field name.
    */
   private static ResourceField getResourceFieldFromName(String fieldName)
   {
      String enumName = fieldName.toUpperCase();
      try
      {
         return ResourceField.valueOf(enumName);
      }
      catch (IllegalArgumentException e)
      {
         return null;
      }
   }

   /**
    * Convert a value to the appropriate type for a resource field.
    */
   private static Object convertValueForResourceField(Object value, ResourceField field)
   {
      // Similar logic to convertValueForField but for resource fields
      if (value == null)
      {
         return null;
      }

      switch (field.getDataType())
      {
         case SHORT:
         case INTEGER:
            Integer intValue = safeIntValue(value);
            if (intValue != null)
            {
               return intValue;
            }
            break;

         case NUMERIC:
         case PERCENTAGE:
         case CURRENCY:
         case UNITS:
            Double doubleValue = safeDoubleValue(value);
            if (doubleValue != null)
            {
               return doubleValue;
            }
            break;

         case BOOLEAN:
            if (value instanceof Boolean)
            {
               return value;
            }
            break;

         case STRING:
            return value.toString();

         case RESOURCE_TYPE:
            if (value instanceof String)
            {
               return ResourceType.valueOf((String) value);
            }
            break;

         default:
            return value;
      }

      return value;
   }

   /**
    * Set up a project from JSON containing property_values, custom_fields, and resources.
    */
   public static ProjectFile setupProjectFromJson(String projectJson) throws IOException
   {
      ProjectFile project = new ProjectFile();
      
      com.fasterxml.jackson.core.JsonFactory factory = new com.fasterxml.jackson.core.JsonFactory();
      com.fasterxml.jackson.core.JsonParser parser = factory.createParser(projectJson);
      
      ProjectProperties props = project.getProjectProperties();
      CustomFieldContainer customFields = project.getCustomFields();
      
      com.fasterxml.jackson.core.JsonToken token = parser.nextToken();
      if (token != com.fasterxml.jackson.core.JsonToken.START_OBJECT)
      {
         throw new IOException("Expected JSON object start");
      }
      
      while (parser.nextToken() != com.fasterxml.jackson.core.JsonToken.END_OBJECT)
      {
         String fieldName = parser.currentName();
         parser.nextToken();
         
         switch (fieldName)
         {
            case "property_values":
               parsePropertyValues(parser, props);
               break;
            case "custom_fields":
               parseCustomFields(parser, customFields);
               break;
            case "resources":
               parseResources(parser, project);
               break;
            default:
               parser.skipChildren();
               break;
         }
      }
      
      parser.close();
      return project;
   }

   private static void parsePropertyValues(com.fasterxml.jackson.core.JsonParser parser, ProjectProperties props) throws IOException
   {
      while (parser.nextToken() != com.fasterxml.jackson.core.JsonToken.END_OBJECT)
      {
         String fieldName = parser.currentName();
         parser.nextToken();
         
         switch (fieldName)
         {
            case "project_title":
               props.setProjectTitle(parser.getText());
               break;
            case "author":
               props.setAuthor(parser.getText());
               break;
            case "start_date":
               props.setStartDate(parseDateTime(parser.getText()));
               break;
            case "status_date":
               props.setStatusDate(parseDateTime(parser.getText()));
               break;
            case "currency_symbol":
               props.setCurrencySymbol(parser.getText());
               break;
            case "currency_code":
               props.setCurrencyCode(parser.getText());
               break;
            case "minutes_per_day":
               props.setMinutesPerDay(Integer.valueOf(parser.getIntValue()));
               break;
            case "minutes_per_week":
               props.setMinutesPerWeek(Integer.valueOf(parser.getIntValue()));
               break;
            case "minutes_per_month":
               props.setMinutesPerMonth(Integer.valueOf(parser.getIntValue()));
               break;
            case "minutes_per_year":
               props.setMinutesPerYear(Integer.valueOf(parser.getIntValue()));
               break;
            case "default_start_time":
               props.setDefaultStartTime(LocalTime.parse(parser.getText()));
               break;
            case "default_end_time":
               props.setDefaultEndTime(LocalTime.parse(parser.getText()));
               break;
            default:
               parser.skipChildren();
               break;
         }
      }
   }

   private static void parseCustomFields(com.fasterxml.jackson.core.JsonParser parser, CustomFieldContainer customFields) throws IOException
   {
      if (parser.getCurrentToken() != com.fasterxml.jackson.core.JsonToken.START_ARRAY)
      {
         return;
      }
      
      while (parser.nextToken() != com.fasterxml.jackson.core.JsonToken.END_ARRAY)
      {
         if (parser.getCurrentToken() != com.fasterxml.jackson.core.JsonToken.START_OBJECT)
         {
            continue;
         }
         
         String fieldType = null;
         String fieldAlias = null;
         String fieldTypeClass = null;
         
         while (parser.nextToken() != com.fasterxml.jackson.core.JsonToken.END_OBJECT)
         {
            String fieldName = parser.currentName();
            parser.nextToken();
            
            switch (fieldName)
            {
               case "field_type":
                  fieldType = parser.getText();
                  break;
               case "field_alias":
                  fieldAlias = parser.getText();
                  break;
               case "field_type_class":
                  fieldTypeClass = parser.getText();
                  break;
               default:
                  break;
            }
         }
         
         // Create custom field if we have the required info
         if ("task".equals(fieldTypeClass) && fieldType != null && fieldAlias != null)
         {
            org.mpxj.TaskField taskField = parseTaskField(fieldType);
            if (taskField != null)
            {
               CustomField customField = customFields.add(taskField);
               customField.setAlias(fieldAlias);
            }
         }
      }
   }

   private static void parseResources(com.fasterxml.jackson.core.JsonParser parser, ProjectFile project) throws IOException
   {
      if (parser.getCurrentToken() != com.fasterxml.jackson.core.JsonToken.START_ARRAY)
      {
         return;
      }
      
      while (parser.nextToken() != com.fasterxml.jackson.core.JsonToken.END_ARRAY)
      {
         if (parser.getCurrentToken() != com.fasterxml.jackson.core.JsonToken.START_OBJECT)
         {
            continue;
         }
         
         Resource resource = project.addResource();
         
         while (parser.nextToken() != com.fasterxml.jackson.core.JsonToken.END_OBJECT)
         {
            String fieldName = parser.currentName();
            parser.nextToken();
            
            switch (fieldName)
            {
               case "name":
                  resource.setName(parser.getText());
                  break;
               case "type":
                  resource.setType(parseResourceType(parser.getText()));
                  break;
               case "active":
                  resource.setActive(parser.getBooleanValue());
                  break;
               case "max_units":
                  // Note: MaxUnits is typically calculated, not set directly
                  break;
               default:
                  parser.skipChildren();
                  break;
            }
         }
      }
   }

   private static org.mpxj.TaskField parseTaskField(String fieldType)
   {
      try
      {
         return org.mpxj.TaskField.valueOf(fieldType.toUpperCase());
      }
      catch (Exception e)
      {
         System.err.println("Warning: Unknown task field type: " + fieldType);
         return null;
      }
   }

   private static org.mpxj.ResourceType parseResourceType(String type)
   {
      try
      {
         return org.mpxj.ResourceType.valueOf(type.toUpperCase());
      }
      catch (Exception e)
      {
         System.err.println("Warning: Unknown resource type: " + type + ", defaulting to WORK");
         return org.mpxj.ResourceType.WORK;
      }
   }

   /**
    * Parse task relations (predecessors or successors) from JSON.
    *
    * @param task target task
    * @param value relation array from JSON
    * @param isPredecessors true for predecessors, false for successors
    */
   private static void parseTaskRelations(Task task, Object value, boolean isPredecessors)
   {
      if (!(value instanceof List))
      {
         System.err.println("Warning: Expected array for " + (isPredecessors ? "predecessors" : "successors"));
         return;
      }

      @SuppressWarnings("unchecked")
      List<Map<String, Object>> relations = (List<Map<String, Object>>) value;
      
      for (Map<String, Object> relationData : relations)
      {
         try
         {
            // Get the related task unique ID
            Integer relatedTaskId = getIntegerFromMap(relationData, "unique_id");
            if (relatedTaskId == null)
            {
               System.err.println("Warning: Missing unique_id in relation");
               continue;
            }

            // Find the related task in the project
            Task relatedTask = findTaskByUniqueId(task.getParentFile(), relatedTaskId);
            if (relatedTask == null)
            {
               System.err.println("Warning: Could not find task with unique_id: " + relatedTaskId);
               continue;
            }

               // Get lag duration (default to 0)
               Duration lag = Duration.getInstance(0, TimeUnit.DAYS);
               Object lagData = relationData.get("lag");
               if (lagData instanceof Duration)
               {
                  // lag is already a Duration object
                  lag = (Duration) lagData;
               }
               else if (lagData instanceof Map)
               {
                  // lag is a map with duration and units
                  @SuppressWarnings("unchecked")
                  Map<String, Object> lagMap = (Map<String, Object>) lagData;
                  Double lagDurationWrapper = getDoubleFromMap(lagMap, "duration");
                  String lagUnits = getStringFromMap(lagMap, "units");
                  if (lagDurationWrapper != null && lagUnits != null)
                  {
                     try
                     {
                        TimeUnit units = TimeUnit.valueOf(lagUnits.toUpperCase());
                        lag = Duration.getInstance(lagDurationWrapper.doubleValue(), units);
                     }
                     catch (Exception e)
                     {
                        System.err.println("Warning: Invalid lag units: " + lagUnits);
                     }
                  }
               }

            // Get relation type (default to FINISH_START)
            String typeStr = getStringFromMap(relationData, "type");
            RelationType type = RelationType.FINISH_START; // Default
            if (typeStr != null)
            {
               try
               {
                  // Convert short form to full form
                  String fullTypeStr = typeStr.toUpperCase();
                  switch (fullTypeStr)
                  {
                     case "FS": fullTypeStr = "FINISH_START"; break;
                     case "SS": fullTypeStr = "START_START"; break;
                     case "FF": fullTypeStr = "FINISH_FINISH"; break;
                     case "SF": fullTypeStr = "START_FINISH"; break;
                  }
                  type = RelationType.valueOf(fullTypeStr);
               }
               catch (Exception e)
               {
                  System.err.println("Warning: Invalid relation type: " + typeStr + ", using default");
               }
            }

            // Create the relation using the builder pattern
            if (isPredecessors)
            {
               // For predecessors: relatedTask is predecessor, task is successor
               Relation.Builder builder = new Relation.Builder()
                  .predecessorTask(relatedTask)
                  .successorTask(task)
                  .type(type)
                  .lag(lag);
               
               // Set notes if provided
               String notes = getStringFromMap(relationData, "notes");
               if (notes != null)
               {
                  builder.notes(notes);
               }
               
               task.addPredecessor(builder);
            }
            else
            {
               // For successors: task is predecessor, relatedTask is successor
               Relation.Builder builder = new Relation.Builder()
                  .predecessorTask(task)
                  .successorTask(relatedTask)
                  .type(type)
                  .lag(lag);
               
               // Set notes if provided
               String notes = getStringFromMap(relationData, "notes");
               if (notes != null)
               {
                  builder.notes(notes);
               }
               
               relatedTask.addPredecessor(builder);
            }
         }
         catch (Exception e)
         {
            System.err.println("Warning: Could not parse relation: " + e.getMessage());
         }
      }
   }

   /**
    * Find a task by its unique ID.
    */
   private static Task findTaskByUniqueId(ProjectFile projectFile, Integer uniqueId)
   {
      for (Task task : projectFile.getTasks())
      {
         if (task.getUniqueID().equals(uniqueId))
         {
            return task;
         }
      }
      return null;
   }

   /**
    * Helper method to get integer from map.
    */
   private static Integer getIntegerFromMap(Map<String, Object> map, String key)
   {
      Object value = map.get(key);
      return safeIntValue(value);
   }

   /**
    * Helper method to get double from map.
    */
   private static Double getDoubleFromMap(Map<String, Object> map, String key)
   {
      Object value = map.get(key);
      return safeDoubleValue(value);
   }

   /**
    * Safely convert a Number object to Double, handling null and various Number types.
    */
   private static Double safeDoubleValue(Object value)
   {
      if (value == null)
      {
         return null;
      }
      if (value instanceof Number)
      {
         return Double.valueOf(((Number) value).doubleValue());
      }
      return null;
   }

   /**
    * Helper method to get string from map.
    */
   private static String getStringFromMap(Map<String, Object> map, String key)
   {
      Object value = map.get(key);
      if (value instanceof String)
      {
         return (String) value;
      }
      return null;
   }

   /**
    * Safely convert a Number object to int, handling null and various Number types.
    */
   private static Integer safeIntValue(Object value)
   {
      if (value == null)
      {
         return null;
      }
      if (value instanceof Number)
      {
         return Integer.valueOf(((Number) value).intValue());
      }
      return null;
   }

   /**
    * Read assignments from a JSON string and add them to the project.
    *
    * @param project target project
    * @param assignmentsJson JSON string containing assignments array
    * @throws IOException if JSON parsing fails
    */
   public static void readAssignments(ProjectFile project, String assignmentsJson) throws IOException
   {
      JsonFactory factory = new JsonFactory();
      try (JsonParser parser = factory.createParser(assignmentsJson))
      {
         parser.nextToken(); // Move to START_OBJECT
         
         while (parser.nextToken() != JsonToken.END_OBJECT)
         {
            String fieldName = parser.currentName();
            if (fieldName == null) continue;
            
            parser.nextToken();
            
            if ("assignments".equals(fieldName) && parser.getCurrentToken() == JsonToken.START_ARRAY)
            {
               while (parser.nextToken() != JsonToken.END_ARRAY)
               {
                  readAssignment(project, parser);
               }
            }
            else
            {
               parser.skipChildren();
            }
         }
      }
   }

   /**
    * Read a single assignment from JSON parser.
    */
   private static void readAssignment(ProjectFile project, JsonParser parser) throws IOException
   {
      // We need to collect the assignment data first, then create the assignment
      Map<String, Object> assignmentData = new HashMap<>();
      
      while (parser.nextToken() != JsonToken.END_OBJECT)
      {
         String fieldName = parser.currentName();
         if (fieldName == null) continue;
         
         parser.nextToken();
         Object value = parseFieldValue(parser);
         assignmentData.put(fieldName, value);
      }
      
      // Now create the assignment with task and resource
      Integer taskId = safeIntValue(assignmentData.get("task_unique_id"));
      Integer resourceId = safeIntValue(assignmentData.get("resource_unique_id"));
      
      if (taskId != null && resourceId != null)
      {
         Task task = findTaskByUniqueId(project, taskId);
         Resource resource = findResourceByUniqueId(project, resourceId);
         
         if (task != null && resource != null)
         {
            ResourceAssignment assignment = task.addResourceAssignment(resource);
            
            // Apply all the field values
            for (Map.Entry<String, Object> entry : assignmentData.entrySet())
            {
               applyFieldToAssignment(assignment, entry.getKey(), entry.getValue());
            }
         }
         else
         {
            System.err.println("Warning: Could not find task (ID: " + taskId + ") or resource (ID: " + resourceId + ") for assignment");
         }
      }
      else
      {
         System.err.println("Warning: Assignment missing task_unique_id or resource_unique_id");
      }
   }

   /**
    * Apply a field value to a resource assignment.
    */
   private static void applyFieldToAssignment(ResourceAssignment assignment, String fieldName, Object value)
   {
      if (value == null)
      {
         return;
      }

      // Handle special fields that need special processing
      switch (fieldName.toLowerCase())
      {
         case "task_unique_id":
         case "resource_unique_id":
            // These are handled during assignment creation, skip them here
            return;
            
         case "assignment_units":
            Double units = safeDoubleValue(value);
            if (units != null)
            {
               assignment.setUnits(units);
            }
            return;
            
         case "remaining_assignment_units":
            Double remainingUnits = safeDoubleValue(value);
            if (remainingUnits != null)
            {
               assignment.setRemainingUnits(remainingUnits);
            }
            return;
            
         case "work":
            if (value instanceof Duration)
            {
               assignment.setWork((Duration) value);
            }
            return;
            
         case "remaining_work":
            if (value instanceof Duration)
            {
               assignment.setRemainingWork((Duration) value);
            }
            return;
            
         case "regular_work":
            if (value instanceof Duration)
            {
               assignment.setRegularWork((Duration) value);
            }
            return;
            
         case "actual_work":
            if (value instanceof Duration)
            {
               assignment.setActualWork((Duration) value);
            }
            return;
            
         case "start":
            if (value instanceof String)
            {
               LocalDateTime startDate = parseDateTime((String) value);
               if (startDate != null)
               {
                  assignment.setStart(startDate);
               }
            }
            return;
            
         case "finish":
            if (value instanceof String)
            {
               LocalDateTime finishDate = parseDateTime((String) value);
               if (finishDate != null)
               {
                  assignment.setFinish(finishDate);
               }
            }
            return;
            
         case "resume":
            if (value instanceof String)
            {
               LocalDateTime resumeDate = parseDateTime((String) value);
               if (resumeDate != null)
               {
                  assignment.setResume(resumeDate);
               }
            }
            return;
            
         case "stop":
            if (value instanceof String)
            {
               LocalDateTime stopDate = parseDateTime((String) value);
               if (stopDate != null)
               {
                  assignment.setStop(stopDate);
               }
            }
            return;
            
         case "guid":
            if (value instanceof String)
            {
               try
               {
                  assignment.setGUID(UUID.fromString((String) value));
               }
               catch (Exception e)
               {
                  System.err.println("Warning: Invalid GUID format: " + value);
               }
            }
            return;
            
         case "created":
            // Created date is typically read-only, skip it
            return;
            
         case "rate_source":
            if (value instanceof String)
            {
               try
               {
                  org.mpxj.RateSource rateSource = org.mpxj.RateSource.valueOf(((String) value).toUpperCase());
                  assignment.setRateSource(rateSource);
               }
               catch (Exception e)
               {
                  System.err.println("Warning: Invalid rate source: " + value);
               }
            }
            return;
            
         case "calculate_costs_from_units":
            if (value instanceof Boolean)
            {
               assignment.setCalculateCostsFromUnits((Boolean) value);
            }
            return;
            
         default:
            // Try to map to AssignmentField enum
            AssignmentField field = getAssignmentFieldFromName(fieldName);
            if (field != null)
            {
               Object convertedValue = convertValueForAssignmentField(value, field);
               if (convertedValue != null)
               {
                  assignment.set(field, convertedValue);
               }
            }
            break;
      }
   }

   /**
    * Get AssignmentField enum from lowercase field name.
    */
   private static AssignmentField getAssignmentFieldFromName(String fieldName)
   {
      String enumName = fieldName.toUpperCase();
      try
      {
         return AssignmentField.valueOf(enumName);
      }
      catch (Exception e)
      {
         return null;
      }
   }

   /**
    * Convert a value to the appropriate type for an assignment field.
    */
   private static Object convertValueForAssignmentField(Object value, AssignmentField field)
   {
      if (value == null)
      {
         return null;
      }

      switch (field.getDataType())
      {
         case SHORT:
         case INTEGER:
            Integer intValue = safeIntValue(value);
            if (intValue != null)
            {
               return intValue;
            }
            break;

         case NUMERIC:
         case PERCENTAGE:
         case CURRENCY:
         case UNITS:
            Double doubleValue = safeDoubleValue(value);
            if (doubleValue != null)
            {
               return doubleValue;
            }
            break;

         case BOOLEAN:
            if (value instanceof Boolean)
            {
               return value;
            }
            break;

         case DATE:
            if (value instanceof String)
            {
               return parseDateTime((String) value);
            }
            break;

         case DURATION:
         case WORK:
         case DELAY:
            if (value instanceof Duration)
            {
               return value;
            }
            break;

         default:
            return value;
      }
      return null;
   }

   /**
    * Find a resource by its unique ID.
    */
   private static Resource findResourceByUniqueId(ProjectFile project, Integer uniqueId)
   {
      for (Resource resource : project.getResources())
      {
         if (uniqueId.equals(resource.getUniqueID()))
         {
            return resource;
         }
      }
      return null;
   }


   /**
    * Read a complete project from a JSON string containing the entire project structure.
    * This method handles property_values, custom_fields, calendars, resources, tasks, and assignments.
    *
    * @param project target project file
    * @param projectJson JSON string containing complete project data
    * @throws IOException if JSON parsing fails
    */
   public static void readProject(ProjectFile project, String projectJson) throws IOException
   {
      JsonFactory factory = new JsonFactory();
      try (JsonParser parser = factory.createParser(projectJson))
      {
         parser.nextToken(); // Move to START_OBJECT
         
         while (parser.nextToken() != JsonToken.END_OBJECT)
         {
            String fieldName = parser.currentName();
            if (fieldName == null) continue;
            
            parser.nextToken();
            
            switch (fieldName)
            {
               case "property_values":
                  parsePropertyValues(parser, project.getProjectProperties());
                  break;
               case "custom_fields":
                  if (parser.getCurrentToken() == JsonToken.START_ARRAY)
                  {
                     parseCustomFields(parser, project.getCustomFields());
                  }
                  break;
               case "calendars":
                  if (parser.getCurrentToken() == JsonToken.START_ARRAY)
                  {
                     while (parser.nextToken() != JsonToken.END_ARRAY)
                     {
                        readCalendarFromParser(project, parser);
                     }
                  }
                  break;
               case "resources":
                  if (parser.getCurrentToken() == JsonToken.START_ARRAY)
                  {
                     while (parser.nextToken() != JsonToken.END_ARRAY)
                     {
                        readResourceFromParser(project, parser);
                     }
                  }
                  break;
               case "tasks":
                  if (parser.getCurrentToken() == JsonToken.START_ARRAY)
                  {
                     while (parser.nextToken() != JsonToken.END_ARRAY)
                     {
                        readTaskFromParser(project, parser);
                     }
                  }
                  break;
               case "assignments":
                  if (parser.getCurrentToken() == JsonToken.START_ARRAY)
                  {
                     while (parser.nextToken() != JsonToken.END_ARRAY)
                     {
                        readAssignment(project, parser);
                     }
                  }
                  break;
               default:
                  parser.skipChildren();
                  break;
            }
         }
      }
   }

   /**
    * Read a calendar from JSON parser.
    * This method is used by readProject to parse calendar objects from a parser.
    *
    * @param project target project file
    * @param parser JSON parser positioned at a calendar object
    * @throws IOException if JSON parsing fails
    */
   private static void readCalendarFromParser(ProjectFile project, JsonParser parser) throws IOException
   {
      ProjectCalendar calendar = project.addCalendar();
      Map<String, Object> fieldValues = new HashMap<>();
      
      // Check if we're already at START_OBJECT, if not, move to it
      JsonToken token = parser.getCurrentToken();
      if (token != JsonToken.START_OBJECT)
      {
         token = parser.nextToken();
         if (token != JsonToken.START_OBJECT)
         {
            throw new IOException("Expected JSON object start");
         }
      }
      
      // Parse the JSON object
      while (parser.nextToken() != JsonToken.END_OBJECT)
      {
         String calendarFieldName = parser.currentName();
         parser.nextToken();
         Object value = parseFieldValue(parser);
         fieldValues.put(calendarFieldName, value);
      }

      // Apply the field values to the calendar
      applyFieldValuesToCalendar(calendar, fieldValues);
   }

   /**
    * Read a resource from JSON parser.
    * This method is used by readProject to parse resource objects from a parser.
    *
    * @param project target project file
    * @param parser JSON parser positioned at a resource object
    * @throws IOException if JSON parsing fails
    */
   private static void readResourceFromParser(ProjectFile project, JsonParser parser) throws IOException
   {
      Resource resource = project.addResource();
      Map<String, Object> fieldValues = new HashMap<>();
      
      // Check if we're already at START_OBJECT, if not, move to it
      JsonToken token = parser.getCurrentToken();
      if (token != JsonToken.START_OBJECT)
      {
         token = parser.nextToken();
         if (token != JsonToken.START_OBJECT)
         {
            throw new IOException("Expected JSON object start");
         }
      }
      
      // Parse the JSON object
      while (parser.nextToken() != JsonToken.END_OBJECT)
      {
         String resourceFieldName = parser.currentName();
         parser.nextToken();
         Object value = parseFieldValue(parser);
         fieldValues.put(resourceFieldName, value);
      }

      // Apply the field values to the resource
      applyFieldValuesToResource(resource, fieldValues);
   }

}
