//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.08.28 at 11:58:30 PM BST
//

package net.sf.mpxj.conceptdraw.schema;

import java.time.LocalDate;
import jakarta.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter4 extends XmlAdapter<String, LocalDate>
{

   @Override
   public LocalDate unmarshal(String value)
   {
      return (net.sf.mpxj.conceptdraw.DatatypeConverter.parseDate(value));
   }

   @Override
   public String marshal(LocalDate value)
   {
      return (net.sf.mpxj.conceptdraw.DatatypeConverter.printDate(value));
   }

}
