//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.06.16 at 11:06:06 AM BST
//

package net.sf.mpxj.conceptdraw.schema;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import net.sf.mpxj.CurrencySymbolPosition;

public class Adapter15 extends XmlAdapter<String, CurrencySymbolPosition>
{

   @Override public CurrencySymbolPosition unmarshal(String value)
   {
      return (net.sf.mpxj.conceptdraw.DatatypeConverter.parseCurrencySymbolPosition(value));
   }

   @Override public String marshal(CurrencySymbolPosition value)
   {
      return (net.sf.mpxj.conceptdraw.DatatypeConverter.printCurrencySymbolPosition(value));
   }

}
