//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.06.16 at 11:06:06 AM BST
//

package net.sf.mpxj.conceptdraw.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * &lt;p&gt;Java class for anonymous complex type.
 *
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 *
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element name="RowHeight" type="{http://www.w3.org/2001/XMLSchema}int"/&amp;gt;
 *         &amp;lt;element name="GridRowStyle"&amp;gt;
 *           &amp;lt;complexType&amp;gt;
 *             &amp;lt;complexContent&amp;gt;
 *               &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *                 &amp;lt;sequence&amp;gt;
 *                   &amp;lt;element name="FontName" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
 *                   &amp;lt;element name="FontSize" type="{http://www.w3.org/2001/XMLSchema}int"/&amp;gt;
 *                 &amp;lt;/sequence&amp;gt;
 *               &amp;lt;/restriction&amp;gt;
 *             &amp;lt;/complexContent&amp;gt;
 *           &amp;lt;/complexType&amp;gt;
 *         &amp;lt;/element&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "", propOrder =
{
   "rowHeight",
   "gridRowStyle"
}) @XmlRootElement(name = "StyleProject") public class StyleProject
{

   @XmlElement(name = "RowHeight", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter6.class) @XmlSchemaType(name = "int") protected Integer rowHeight;
   @XmlElement(name = "GridRowStyle", required = true) protected StyleProject.GridRowStyle gridRowStyle;

   /**
    * Gets the value of the rowHeight property.
    *
    * @return
    *     possible object is
    *     {@link String }
    *
    */
   public Integer getRowHeight()
   {
      return rowHeight;
   }

   /**
    * Sets the value of the rowHeight property.
    *
    * @param value
    *     allowed object is
    *     {@link String }
    *
    */
   public void setRowHeight(Integer value)
   {
      this.rowHeight = value;
   }

   /**
    * Gets the value of the gridRowStyle property.
    *
    * @return
    *     possible object is
    *     {@link StyleProject.GridRowStyle }
    *
    */
   public StyleProject.GridRowStyle getGridRowStyle()
   {
      return gridRowStyle;
   }

   /**
    * Sets the value of the gridRowStyle property.
    *
    * @param value
    *     allowed object is
    *     {@link StyleProject.GridRowStyle }
    *
    */
   public void setGridRowStyle(StyleProject.GridRowStyle value)
   {
      this.gridRowStyle = value;
   }

   /**
    * &lt;p&gt;Java class for anonymous complex type.
    *
    * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
    *
    * &lt;pre&gt;
    * &amp;lt;complexType&amp;gt;
    *   &amp;lt;complexContent&amp;gt;
    *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
    *       &amp;lt;sequence&amp;gt;
    *         &amp;lt;element name="FontName" type="{http://www.w3.org/2001/XMLSchema}string"/&amp;gt;
    *         &amp;lt;element name="FontSize" type="{http://www.w3.org/2001/XMLSchema}int"/&amp;gt;
    *       &amp;lt;/sequence&amp;gt;
    *     &amp;lt;/restriction&amp;gt;
    *   &amp;lt;/complexContent&amp;gt;
    * &amp;lt;/complexType&amp;gt;
    * &lt;/pre&gt;
    *
    *
    */
   @XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "", propOrder =
   {
      "fontName",
      "fontSize"
   }) public static class GridRowStyle
   {

      @XmlElement(name = "FontName", required = true) protected String fontName;
      @XmlElement(name = "FontSize", required = true, type = String.class) @XmlJavaTypeAdapter(Adapter6.class) @XmlSchemaType(name = "int") protected Integer fontSize;

      /**
       * Gets the value of the fontName property.
       *
       * @return
       *     possible object is
       *     {@link String }
       *
       */
      public String getFontName()
      {
         return fontName;
      }

      /**
       * Sets the value of the fontName property.
       *
       * @param value
       *     allowed object is
       *     {@link String }
       *
       */
      public void setFontName(String value)
      {
         this.fontName = value;
      }

      /**
       * Gets the value of the fontSize property.
       *
       * @return
       *     possible object is
       *     {@link String }
       *
       */
      public Integer getFontSize()
      {
         return fontSize;
      }

      /**
       * Sets the value of the fontSize property.
       *
       * @param value
       *     allowed object is
       *     {@link String }
       *
       */
      public void setFontSize(Integer value)
      {
         this.fontSize = value;
      }

   }

}
