/*
 * file:       FieldMap9.java
 * author:     Jon Iles
 * copyright:  (c) Packwood Software 2011
 * date:       13/04/2010
 */

/*
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
 */

package net.sf.mpxj.mpp;

import net.sf.mpxj.AssignmentField;
import net.sf.mpxj.FieldType;
import net.sf.mpxj.ProjectFile;
import net.sf.mpxj.ResourceField;
import net.sf.mpxj.TaskField;
import net.sf.mpxj.utility.FieldTypeUtility;

/**
 * MPP9 field map.
 */
class FieldMap9 extends FieldMap
{
   /**
    * Constructor.
    * 
    * @param file parent file
    */
   public FieldMap9(ProjectFile file)
   {
      super(file);
   }

   /**
    * {@inheritDoc}
    */
   @Override protected FieldType getFieldType(int fieldID)
   {
      return FieldTypeUtility.getInstance(fieldID);
   }

   /**
    * {@inheritDoc}
    */
   @Override protected boolean useTypeAsVarDataKey()
   {
      return false;
   }

   /**
    * {@inheritDoc}
    */
   @Override protected Object[][] getDefaultTaskData()
   {
      return DEFAULT_TASK_MAP;
   }

   /**
    * {@inheritDoc}
    */
   @Override protected Object[][] getDefaultResourceData()
   {
      return DEFAULT_RESOURCE_MAP;
   }

   /**
    * {@inheritDoc}
    */
   @Override protected Object[][] getDefaultAssignmentData()
   {
      return DEFAULT_ASSIGNMENT_MAP;
   }

   /**
    * Default task data.
    */
   private static final Object[][] DEFAULT_TASK_MAP =
   {
      {
         TaskField.UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(0),
         Integer.valueOf(0)
      },
      {
         TaskField.ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(4),
         Integer.valueOf(0)
      },
      {
         TaskField.EARLY_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(8),
         Integer.valueOf(0)
      },
      {
         TaskField.LATE_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(12),
         Integer.valueOf(0)
      },
      {
         TaskField.STOP,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(16),
         Integer.valueOf(0)
      },
      {
         TaskField.RESUME,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(20),
         Integer.valueOf(0)
      },
      {
         TaskField.FREE_SLACK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(24),
         Integer.valueOf(0)
      },
      {
         TaskField.START_SLACK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(28),
         Integer.valueOf(0)
      },
      {
         TaskField.FINISH_SLACK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(32),
         Integer.valueOf(0)
      },
      {
         TaskField.OUTLINE_LEVEL,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(40),
         Integer.valueOf(0)
      },
      {
         TaskField.DURATION_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(58),
         Integer.valueOf(0)
      },
      {
         TaskField.DURATION,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(60),
         Integer.valueOf(0)
      },
      {
         TaskField.ACTUAL_DURATION_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(64),
         Integer.valueOf(0)
      },
      {
         TaskField.ACTUAL_DURATION,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(66),
         Integer.valueOf(0)
      },
      {
         TaskField.REMAINING_DURATION,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(70),
         Integer.valueOf(0)
      },
      {
         TaskField.BASELINE_DURATION,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(74),
         Integer.valueOf(0)
      },
      {
         TaskField.BASELINE_DURATION_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(78),
         Integer.valueOf(0)
      },
      {
         TaskField.CONSTRAINT_TYPE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(80),
         Integer.valueOf(0)
      },
      {
         TaskField.LEVELING_DELAY,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(82),
         Integer.valueOf(0)
      },
      {
         TaskField.LEVELING_DELAY_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(86),
         Integer.valueOf(0)
      },
      {
         TaskField.START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(88),
         Integer.valueOf(0)
      },
      {
         TaskField.FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(92),
         Integer.valueOf(0)
      },
      {
         TaskField.ACTUAL_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(96),
         Integer.valueOf(0)
      },
      {
         TaskField.ACTUAL_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(100),
         Integer.valueOf(0)
      },
      {
         TaskField.BASELINE_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(104),
         Integer.valueOf(0)
      },
      {
         TaskField.BASELINE_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(108),
         Integer.valueOf(0)
      },
      {
         TaskField.CONSTRAINT_DATE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(112),
         Integer.valueOf(0)
      },
      {
         TaskField.PRIORITY,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(120),
         Integer.valueOf(0)
      },
      {
         TaskField.PERCENT_COMPLETE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(122),
         Integer.valueOf(0)
      },
      {
         TaskField.PERCENT_WORK_COMPLETE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(124),
         Integer.valueOf(0)
      },
      {
         TaskField.TYPE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(126),
         Integer.valueOf(0)
      },
      {
         TaskField.FIXED_COST_ACCRUAL,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(128),
         Integer.valueOf(0)
      },
      {
         TaskField.CREATED,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(130),
         Integer.valueOf(0)
      },
      {
         TaskField.RECURRING,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(134),
         Integer.valueOf(0)
      },
      {
         TaskField.PRELEVELED_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(136),
         Integer.valueOf(0)
      },
      {
         TaskField.PRELEVELED_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(140),
         Integer.valueOf(0)
      },
      {
         TaskField.EARLY_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(148),
         Integer.valueOf(0)
      },
      {
         TaskField.LATE_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(152),
         Integer.valueOf(0)
      },
      {
         TaskField.SUMMARY_PROGRESS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(156),
         Integer.valueOf(0)
      },
      {
         TaskField.DEADLINE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(164),
         Integer.valueOf(0)
      },
      {
         TaskField.WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(168),
         Integer.valueOf(0)
      },
      {
         TaskField.BASELINE_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(176),
         Integer.valueOf(0)
      },
      {
         TaskField.ACTUAL_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(184),
         Integer.valueOf(0)
      },
      {
         TaskField.REMAINING_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(192),
         Integer.valueOf(0)
      },
      {
         TaskField.COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(200),
         Integer.valueOf(0)
      },
      {
         TaskField.FIXED_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(208),
         Integer.valueOf(0)
      },
      {
         TaskField.ACTUAL_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(216),
         Integer.valueOf(0)
      },
      {
         TaskField.REMAINING_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(224),
         Integer.valueOf(0)
      },
      {
         TaskField.BASELINE_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(232),
         Integer.valueOf(0)
      },
      {
         TaskField.BASELINE_FIXED_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(256),
         Integer.valueOf(0)
      },
      {
         TaskField.ACTUAL_OVERTIME_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(3)
      },
      {
         TaskField.REMAINING_OVERTIME_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(4)
      },
      {
         TaskField.OVERTIME_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(5)
      },
      {
         TaskField.ACTUAL_OVERTIME_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(6)
      },
      {
         TaskField.REMAINING_OVERTIME_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(7)
      },
      {
         TaskField.SUBPROJECT_TASKS_UNIQUEID_OFFSET,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(8)
      },
      {
         TaskField.SUBPROJECT_UNIQUE_TASK_ID,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(9)
      },
      {
         TaskField.WBS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(10)
      },
      {
         TaskField.NAME,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(11)
      },
      {
         TaskField.CONTACT,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(12)
      },
      {
         TaskField.TEXT1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(14)
      },
      {
         TaskField.TEXT2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(15)
      },
      {
         TaskField.TEXT3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(16)
      },
      {
         TaskField.TEXT4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(17)
      },
      {
         TaskField.TEXT5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(18)
      },
      {
         TaskField.TEXT6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(19)
      },
      {
         TaskField.TEXT7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(20)
      },
      {
         TaskField.TEXT8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(21)
      },
      {
         TaskField.TEXT9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(22)
      },
      {
         TaskField.TEXT10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(23)
      },
      {
         TaskField.START1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(24)
      },
      {
         TaskField.FINISH1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(25)
      },
      {
         TaskField.START2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(26)
      },
      {
         TaskField.FINISH2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(27)
      },
      {
         TaskField.START3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(28)
      },
      {
         TaskField.FINISH3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(29)
      },
      {
         TaskField.START4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(30)
      },
      {
         TaskField.FINISH4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(31)
      },
      {
         TaskField.START5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(32)
      },
      {
         TaskField.FINISH5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(33)
      },
      {
         TaskField.START6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(34)
      },
      {
         TaskField.FINISH6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(35)
      },
      {
         TaskField.START7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(36)
      },
      {
         TaskField.FINISH7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(37)
      },
      {
         TaskField.START8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(38)
      },
      {
         TaskField.FINISH8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(39)
      },
      {
         TaskField.START9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(40)
      },
      {
         TaskField.FINISH9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(41)
      },
      {
         TaskField.START10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(42)
      },
      {
         TaskField.FINISH10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(43)
      },
      {
         TaskField.NUMBER1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(45)
      },
      {
         TaskField.NUMBER2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(46)
      },
      {
         TaskField.NUMBER3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(47)
      },
      {
         TaskField.NUMBER4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(48)
      },
      {
         TaskField.NUMBER5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(49)
      },
      {
         TaskField.NUMBER6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(50)
      },
      {
         TaskField.NUMBER7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(51)
      },
      {
         TaskField.NUMBER8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(52)
      },
      {
         TaskField.NUMBER9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(53)
      },
      {
         TaskField.NUMBER10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(54)
      },
      {
         TaskField.DURATION1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(55)
      },
      {
         TaskField.DURATION1_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(56)
      },
      {
         TaskField.DURATION2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(57)
      },
      {
         TaskField.DURATION2_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(58)
      },
      {
         TaskField.DURATION3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(59)
      },
      {
         TaskField.DURATION3_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(60)
      },
      {
         TaskField.DURATION4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(61)
      },
      {
         TaskField.DURATION4_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(62)
      },
      {
         TaskField.DURATION5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(63)
      },
      {
         TaskField.DURATION5_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(64)
      },
      {
         TaskField.DURATION6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(65)
      },
      {
         TaskField.DURATION6_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(66)
      },
      {
         TaskField.DURATION7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(67)
      },
      {
         TaskField.DURATION7_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(68)
      },
      {
         TaskField.DURATION8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(69)
      },
      {
         TaskField.DURATION8_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(70)
      },
      {
         TaskField.DURATION9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(71)
      },
      {
         TaskField.DURATION9_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(72)
      },
      {
         TaskField.DURATION10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(73)
      },
      {
         TaskField.DURATION10_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(74)
      },
      {
         TaskField.RECURRING_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(76)
      },
      {
         TaskField.SUBPROJECT_TASK_ID,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(79)
      },
      {
         TaskField.DATE1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(80)
      },
      {
         TaskField.DATE2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(81)
      },
      {
         TaskField.DATE3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(82)
      },
      {
         TaskField.DATE4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(83)
      },
      {
         TaskField.DATE5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(84)
      },
      {
         TaskField.DATE6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(85)
      },
      {
         TaskField.DATE7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(86)
      },
      {
         TaskField.DATE8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(87)
      },
      {
         TaskField.DATE9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(88)
      },
      {
         TaskField.DATE10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(89)
      },
      {
         TaskField.TEXT11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(90)
      },
      {
         TaskField.TEXT12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(91)
      },
      {
         TaskField.TEXT13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(92)
      },
      {
         TaskField.TEXT14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(93)
      },
      {
         TaskField.TEXT15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(94)
      },
      {
         TaskField.TEXT16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(95)
      },
      {
         TaskField.TEXT17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(96)
      },
      {
         TaskField.TEXT18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(97)
      },
      {
         TaskField.TEXT19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(98)
      },
      {
         TaskField.TEXT20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(99)
      },
      {
         TaskField.TEXT21,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(100)
      },
      {
         TaskField.TEXT22,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(101)
      },
      {
         TaskField.TEXT23,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(102)
      },
      {
         TaskField.TEXT24,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(103)
      },
      {
         TaskField.TEXT25,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(104)
      },
      {
         TaskField.TEXT26,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(105)
      },
      {
         TaskField.TEXT27,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(106)
      },
      {
         TaskField.TEXT28,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(107)
      },
      {
         TaskField.TEXT29,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(108)
      },
      {
         TaskField.TEXT30,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(109)
      },
      {
         TaskField.NUMBER11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(110)
      },
      {
         TaskField.NUMBER12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(111)
      },
      {
         TaskField.NUMBER13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(112)
      },
      {
         TaskField.NUMBER14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(113)
      },
      {
         TaskField.NUMBER15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(114)
      },
      {
         TaskField.NUMBER16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(115)
      },
      {
         TaskField.NUMBER17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(116)
      },
      {
         TaskField.NUMBER18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(117)
      },
      {
         TaskField.NUMBER19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(118)
      },
      {
         TaskField.NUMBER20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(119)
      },
      {
         TaskField.OUTLINE_CODE1_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(123)
      },
      {
         TaskField.OUTLINE_CODE2_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(124)
      },
      {
         TaskField.OUTLINE_CODE3_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(125)
      },
      {
         TaskField.OUTLINE_CODE4_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(126)
      },
      {
         TaskField.OUTLINE_CODE5_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(127)
      },
      {
         TaskField.OUTLINE_CODE6_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(128)
      },
      {
         TaskField.OUTLINE_CODE7_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(129)
      },
      {
         TaskField.OUTLINE_CODE8_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(130)
      },
      {
         TaskField.OUTLINE_CODE9_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(131)
      },
      {
         TaskField.OUTLINE_CODE10_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(132)
      },
      {
         TaskField.HYPERLINK_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(133)
      },
      {
         TaskField.COST1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(134)
      },
      {
         TaskField.COST2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(135)
      },
      {
         TaskField.COST3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(136)
      },
      {
         TaskField.COST4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(137)
      },
      {
         TaskField.COST5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(138)
      },
      {
         TaskField.COST6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(139)
      },
      {
         TaskField.COST7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(140)
      },
      {
         TaskField.COST8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(141)
      },
      {
         TaskField.COST9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(142)
      },
      {
         TaskField.COST10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(143)
      },
      {
         TaskField.NOTES,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(144)
      },
      {
         TaskField.SUBPROJECT_FILE,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(160)
      },
      {
         TaskField.ENTERPRISE_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(163)
      },
      {
         TaskField.CALENDAR_UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(160),
         Integer.valueOf(0)
      }
   };

   private static final Object[][] DEFAULT_RESOURCE_MAP =
   {

      {
         ResourceField.UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(0),
         Integer.valueOf(0)
      },
      {
         ResourceField.ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(4),
         Integer.valueOf(0)
      },
      {
         ResourceField.ACCRUE_AT,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(12),
         Integer.valueOf(0)
      },
      {
         ResourceField.WORKGROUP,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(14),
         Integer.valueOf(0)
      },
      {
         ResourceField.AVAILABLE_FROM,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(20),
         Integer.valueOf(0)
      },
      {
         ResourceField.AVAILABLE_TO,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(24),
         Integer.valueOf(0)
      },
      {
         ResourceField.STANDARD_RATE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(28),
         Integer.valueOf(0)
      },
      {
         ResourceField.OVERTIME_RATE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(36),
         Integer.valueOf(0)
      },
      {
         ResourceField.MAX_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(44),
         Integer.valueOf(0)
      },
      {
         ResourceField.WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(52),
         Integer.valueOf(0)
      },
      {
         ResourceField.ACTUAL_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(60),
         Integer.valueOf(0)
      },
      {
         ResourceField.BASELINE_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(68),
         Integer.valueOf(0)
      },
      {
         ResourceField.OVERTIME_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(76),
         Integer.valueOf(0)
      },
      {
         ResourceField.COST_PER_USE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(84),
         Integer.valueOf(0)
      },
      {
         ResourceField.REMAINING_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(92),
         Integer.valueOf(0)
      },
      {
         ResourceField.REGULAR_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(100),
         Integer.valueOf(0)
      },
      {
         ResourceField.ACTUAL_OVERTIME_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(108),
         Integer.valueOf(0)
      },
      {
         ResourceField.REMAINING_OVERTIME_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(116),
         Integer.valueOf(0)
      },
      {
         ResourceField.PEAK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(124),
         Integer.valueOf(0)
      },
      {
         ResourceField.ACTUAL_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(132),
         Integer.valueOf(0)
      },
      {
         ResourceField.COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(140),
         Integer.valueOf(0)
      },
      {
         ResourceField.BASELINE_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(148),
         Integer.valueOf(0)
      },
      {
         ResourceField.REMAINING_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(156),
         Integer.valueOf(0)
      },
      {
         ResourceField.OVERTIME_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(164),
         Integer.valueOf(0)
      },
      {
         ResourceField.ACTUAL_OVERTIME_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(172),
         Integer.valueOf(0)
      },
      {
         ResourceField.REMAINING_OVERTIME_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(180),
         Integer.valueOf(0)
      },
      {
         ResourceField.NAME,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1)
      },
      {
         ResourceField.INITIALS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(3)
      },
      {
         ResourceField.GROUP,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(4)
      },
      {
         ResourceField.CODE,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(5)
      },
      {
         ResourceField.EMAIL_ADDRESS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(6)
      },
      {
         ResourceField.PHONETICS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(7)
      },
      {
         ResourceField.MATERIAL_LABEL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(8)
      },
      {
         ResourceField.WINDOWS_USER_ACCOUNT,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(9)
      },
      {
         ResourceField.TEXT1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(10)
      },
      {
         ResourceField.TEXT2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(11)
      },
      {
         ResourceField.TEXT3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(12)
      },
      {
         ResourceField.TEXT4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(13)
      },
      {
         ResourceField.TEXT5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(14)
      },
      {
         ResourceField.TEXT6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(15)
      },
      {
         ResourceField.TEXT7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(16)
      },
      {
         ResourceField.TEXT8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(17)
      },
      {
         ResourceField.TEXT9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(18)
      },
      {
         ResourceField.TEXT10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(19)
      },
      {
         ResourceField.TEXT11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(20)
      },
      {
         ResourceField.TEXT12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(21)
      },
      {
         ResourceField.TEXT13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(22)
      },
      {
         ResourceField.TEXT14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(23)
      },
      {
         ResourceField.TEXT15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(24)
      },
      {
         ResourceField.TEXT16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(25)
      },
      {
         ResourceField.TEXT17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(26)
      },
      {
         ResourceField.TEXT18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(27)
      },
      {
         ResourceField.TEXT19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(28)
      },
      {
         ResourceField.TEXT20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(29)
      },
      {
         ResourceField.TEXT21,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(30)
      },
      {
         ResourceField.TEXT22,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(31)
      },
      {
         ResourceField.TEXT23,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(32)
      },
      {
         ResourceField.TEXT24,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(33)
      },
      {
         ResourceField.TEXT25,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(34)
      },
      {
         ResourceField.TEXT26,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(35)
      },
      {
         ResourceField.TEXT27,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(36)
      },
      {
         ResourceField.TEXT28,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(37)
      },
      {
         ResourceField.TEXT29,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(38)
      },
      {
         ResourceField.TEXT30,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(39)
      },
      {
         ResourceField.START1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(40)
      },
      {
         ResourceField.START2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(41)
      },
      {
         ResourceField.START3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(42)
      },
      {
         ResourceField.START4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(43)
      },
      {
         ResourceField.START5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(44)
      },
      {
         ResourceField.START6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(45)
      },
      {
         ResourceField.START7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(46)
      },
      {
         ResourceField.START8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(47)
      },
      {
         ResourceField.START9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(48)
      },
      {
         ResourceField.START10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(49)
      },
      {
         ResourceField.FINISH1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(50)
      },
      {
         ResourceField.FINISH2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(51)
      },
      {
         ResourceField.FINISH3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(52)
      },
      {
         ResourceField.FINISH4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(53)
      },
      {
         ResourceField.FINISH5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(54)
      },
      {
         ResourceField.FINISH6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(55)
      },
      {
         ResourceField.FINISH7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(56)
      },
      {
         ResourceField.FINISH8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(57)
      },
      {
         ResourceField.FINISH9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(58)
      },
      {
         ResourceField.FINISH10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(59)
      },
      {
         ResourceField.NUMBER1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(60)
      },
      {
         ResourceField.NUMBER2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(61)
      },
      {
         ResourceField.NUMBER3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(62)
      },
      {
         ResourceField.NUMBER4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(63)
      },
      {
         ResourceField.NUMBER5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(64)
      },
      {
         ResourceField.NUMBER6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(65)
      },
      {
         ResourceField.NUMBER7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(66)
      },
      {
         ResourceField.NUMBER8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(67)
      },
      {
         ResourceField.NUMBER9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(68)
      },
      {
         ResourceField.NUMBER10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(69)
      },
      {
         ResourceField.NUMBER11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(70)
      },
      {
         ResourceField.NUMBER12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(71)
      },
      {
         ResourceField.NUMBER13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(72)
      },
      {
         ResourceField.NUMBER14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(73)
      },
      {
         ResourceField.NUMBER15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(74)
      },
      {
         ResourceField.NUMBER16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(75)
      },
      {
         ResourceField.NUMBER17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(76)
      },
      {
         ResourceField.NUMBER18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(77)
      },
      {
         ResourceField.NUMBER19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(78)
      },
      {
         ResourceField.NUMBER20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(79)
      },
      {
         ResourceField.DURATION1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(80)
      },
      {
         ResourceField.DURATION2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(81)
      },
      {
         ResourceField.DURATION3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(82)
      },
      {
         ResourceField.DURATION4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(83)
      },
      {
         ResourceField.DURATION5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(84)
      },
      {
         ResourceField.DURATION6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(85)
      },
      {
         ResourceField.DURATION7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(86)
      },
      {
         ResourceField.DURATION8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(87)
      },
      {
         ResourceField.DURATION9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(88)
      },
      {
         ResourceField.DURATION10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(89)
      },
      {
         ResourceField.DURATION1_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(90)
      },
      {
         ResourceField.DURATION2_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(91)
      },
      {
         ResourceField.DURATION3_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(92)
      },
      {
         ResourceField.DURATION4_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(93)
      },
      {
         ResourceField.DURATION5_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(94)
      },
      {
         ResourceField.DURATION6_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(95)
      },
      {
         ResourceField.DURATION7_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(96)
      },
      {
         ResourceField.DURATION8_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(97)
      },
      {
         ResourceField.DURATION9_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(98)
      },
      {
         ResourceField.DURATION10_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(99)
      },
      {
         ResourceField.SUBPROJECT_RESOURCE_UNIQUE_ID,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(102)
      },
      {
         ResourceField.DATE1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(103)
      },
      {
         ResourceField.DATE2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(104)
      },
      {
         ResourceField.DATE3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(105)
      },
      {
         ResourceField.DATE4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(106)
      },
      {
         ResourceField.DATE5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(107)
      },
      {
         ResourceField.DATE6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(108)
      },
      {
         ResourceField.DATE7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(109)
      },
      {
         ResourceField.DATE8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(110)
      },
      {
         ResourceField.DATE9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(111)
      },
      {
         ResourceField.DATE10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(112)
      },
      {
         ResourceField.OUTLINE_CODE1_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(113)
      },
      {
         ResourceField.OUTLINE_CODE2_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(114)
      },
      {
         ResourceField.OUTLINE_CODE3_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(115)
      },
      {
         ResourceField.OUTLINE_CODE4_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(116)
      },
      {
         ResourceField.OUTLINE_CODE5_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(117)
      },
      {
         ResourceField.OUTLINE_CODE6_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(118)
      },
      {
         ResourceField.OUTLINE_CODE7_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(119)
      },
      {
         ResourceField.OUTLINE_CODE8_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(120)
      },
      {
         ResourceField.OUTLINE_CODE9_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(121)
      },
      {
         ResourceField.OUTLINE_CODE10_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(122)
      },
      {
         ResourceField.HYPERLINK_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(123)
      },
      {
         ResourceField.NOTES,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(124)
      },
      {
         ResourceField.COST1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(125)
      },
      {
         ResourceField.COST2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(126)
      },
      {
         ResourceField.COST3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(127)
      },
      {
         ResourceField.COST4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(128)
      },
      {
         ResourceField.COST5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(129)
      },
      {
         ResourceField.COST6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(130)
      },
      {
         ResourceField.COST7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(131)
      },
      {
         ResourceField.COST8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(132)
      },
      {
         ResourceField.COST9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(133)
      },
      {
         ResourceField.COST10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(134)
      },
      {
         ResourceField.COST_RATE_A,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(135)
      },
      {
         ResourceField.COST_RATE_B,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(136)
      },
      {
         ResourceField.COST_RATE_C,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(137)
      },
      {
         ResourceField.COST_RATE_D,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(138)
      },
      {
         ResourceField.COST_RATE_E,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(139)
      },
      {
         ResourceField.AVAILABILITY_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(142)
      },
      {
         ResourceField.ENTERPRISE_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(143)
      },
      {
         ResourceField.BASELINE1_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(144)
      },
      {
         ResourceField.BASELINE1_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(145)
      },
      {
         ResourceField.BASELINE2_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(148)
      },
      {
         ResourceField.BASELINE2_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(149)
      },
      {
         ResourceField.BASELINE3_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(152)
      },
      {
         ResourceField.BASELINE3_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(153)
      },
      {
         ResourceField.BASELINE4_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(156)
      },
      {
         ResourceField.BASELINE4_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(157)
      },
      {
         ResourceField.BASELINE5_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(160)
      },
      {
         ResourceField.BASELINE5_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(161)
      },
      {
         ResourceField.BASELINE6_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(164)
      },
      {
         ResourceField.BASELINE6_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(165)
      },
      {
         ResourceField.BASELINE7_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(168)
      },
      {
         ResourceField.BASELINE7_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(169)
      },
      {
         ResourceField.BASELINE8_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(172)
      },
      {
         ResourceField.BASELINE8_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(173)
      },
      {
         ResourceField.BASELINE9_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(176)
      },
      {
         ResourceField.BASELINE9_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(177)
      },
      {
         ResourceField.BASELINE10_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(180)
      },
      {
         ResourceField.BASELINE10_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(181)
      },
      {
         ResourceField.ENTERPRISE_UNIQUE_ID,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(185)
      }
   };

   private static final Object[][] DEFAULT_ASSIGNMENT_MAP =
   {
      {
         AssignmentField.UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(0),
         Integer.valueOf(0)
      },
      {
         AssignmentField.TASK_UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(4),
         Integer.valueOf(0)
      },
      {
         AssignmentField.RESOURCE_UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(8),
         Integer.valueOf(0)
      },
      {
         AssignmentField.START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(12),
         Integer.valueOf(0)
      },
      {
         AssignmentField.FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(16),
         Integer.valueOf(0)
      },
      {
         AssignmentField.ASSIGNMENT_DELAY,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(24),
         Integer.valueOf(0)
      },
      {
         AssignmentField.LEVELING_DELAY_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(28),
         Integer.valueOf(0)
      },
      {
         AssignmentField.LEVELING_DELAY,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(30),
         Integer.valueOf(0)
      },
      {
         AssignmentField.BASELINE_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(36),
         Integer.valueOf(0)
      },
      {
         AssignmentField.BASELINE_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(40),
         Integer.valueOf(0)
      },
      {
         AssignmentField.VARIABLE_RATE_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(52),
         Integer.valueOf(0)
      },
      {
         AssignmentField.ASSIGNMENT_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(54),
         Integer.valueOf(0)
      },
      {
         AssignmentField.WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(62),
         Integer.valueOf(0)
      },
      {
         AssignmentField.ACTUAL_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(70),
         Integer.valueOf(0)
      },
      {
         AssignmentField.REMAINING_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(86),
         Integer.valueOf(0)
      },
      {
         AssignmentField.BASELINE_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(94),
         Integer.valueOf(0)
      },
      {
         AssignmentField.COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(102),
         Integer.valueOf(0)
      },
      {
         AssignmentField.ACTUAL_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(110),
         Integer.valueOf(0)
      },
      {
         AssignmentField.BASELINE_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(126),
         Integer.valueOf(0)
      },
      {
         AssignmentField.PLANNED_WORK_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(7)
      },
      {
         AssignmentField.COMPLETE_WORK_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(9)
      }
   };
}
