/*
 * file:       FieldMap12.java
 * author:     Jon Iles
 * copyright:  (c) Packwood Software 2011
 * date:       13/04/2010
 */

/*
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
 */

package net.sf.mpxj.mpp;

import net.sf.mpxj.AssignmentField;
import net.sf.mpxj.ProjectFile;
import net.sf.mpxj.TaskField;

/**
 * MPP12 field map.
 */
class FieldMap12 extends FieldMap
{
   /**
    * Constructor.
    * 
    * @param file parent file
    */
   public FieldMap12(ProjectFile file)
   {
      super(file);
   }

   /**
    * {@inheritDoc}
    */
   @Override protected boolean useTypeAsVarDataKey()
   {
      return true;
   }

   /**
    * {@inheritDoc}
    */
   @Override protected Object[][] getDefaultTaskData()
   {
      return DEFAULT_TASK_MAP;
   }

   /**
    * {@inheritDoc}
    */
   @Override protected Object[][] getDefaultResourceData()
   {
      return null;
   }

   /**
    * {@inheritDoc}
    */
   @Override protected Object[][] getDefaultAssignmentData()
   {
      return DEFAULT_ASSIGNMENT_MAP;
   }

   private static final Object[][] DEFAULT_ASSIGNMENT_MAP =
   {
      {
         AssignmentField.UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(0),
         Integer.valueOf(0)
      },
      {
         AssignmentField.TASK_UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(4),
         Integer.valueOf(0)
      },
      {
         AssignmentField.RESOURCE_UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(8),
         Integer.valueOf(0)
      },
      {
         AssignmentField.START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(12),
         Integer.valueOf(0)
      },
      {
         AssignmentField.FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(16),
         Integer.valueOf(0)
      },
      {
         AssignmentField.ASSIGNMENT_DELAY,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(24),
         Integer.valueOf(0)
      },
      {
         AssignmentField.LEVELING_DELAY_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(28),
         Integer.valueOf(0)
      },
      {
         AssignmentField.LEVELING_DELAY,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(30),
         Integer.valueOf(0)
      },
      {
         AssignmentField.BASELINE_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(36),
         Integer.valueOf(0)
      },
      {
         AssignmentField.BASELINE_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(40),
         Integer.valueOf(0)
      },
      {
         AssignmentField.VARIABLE_RATE_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(52),
         Integer.valueOf(0)
      },
      {
         AssignmentField.ASSIGNMENT_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(54),
         Integer.valueOf(0)
      },
      {
         AssignmentField.WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(62),
         Integer.valueOf(0)
      },
      {
         AssignmentField.ACTUAL_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(70),
         Integer.valueOf(0)
      },
      {
         AssignmentField.REMAINING_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(86),
         Integer.valueOf(0)
      },
      {
         AssignmentField.BASELINE_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(94),
         Integer.valueOf(0)
      },
      {
         AssignmentField.COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(102),
         Integer.valueOf(0)
      },
      {
         AssignmentField.ACTUAL_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(110),
         Integer.valueOf(0)
      },
      {
         AssignmentField.BASELINE_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(126),
         Integer.valueOf(0)
      },
      {
         AssignmentField.PLANNED_WORK_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(7)
      },
      {
         AssignmentField.COMPLETE_WORK_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(9)
      }

   };

   public static final Object[][] DEFAULT_TASK_MAP =
   {
      {
         TaskField.UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(0),
         Integer.valueOf(86)
      },
      {
         TaskField.ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(4),
         Integer.valueOf(23)
      },
      {
         TaskField.LINKED_FIELDS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(98)
      },
      {
         TaskField.MILESTONE,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(24)
      },
      {
         TaskField.CRITICAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(19)
      },
      {
         TaskField.SUMMARY,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(92)
      },
      {
         TaskField.MARKED,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(71)
      },
      {
         TaskField.IGNORE_RESOURCE_CALENDAR,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(399)
      },
      {
         TaskField.ROLLUP,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(82)
      },
      {
         TaskField.HIDEBAR,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(109)
      },
      {
         TaskField.RECURRING,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(129)
      },
      {
         TaskField.EXTERNAL_TASK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(232)
      },
      {
         TaskField.EFFORT_DRIVEN,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(132)
      },
      {
         TaskField.SUBPROJECT_READ_ONLY,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(246)
      },
      {
         TaskField.LEVELING_CAN_SPLIT,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(252)
      },
      {
         TaskField.LEVEL_ASSIGNMENTS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(253)
      },
      {
         TaskField.ESTIMATED,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(396)
      },
      {
         TaskField.EARLY_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(8),
         Integer.valueOf(38)
      },
      {
         TaskField.LATE_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(12),
         Integer.valueOf(39)
      },
      {
         TaskField.STOP,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(16),
         Integer.valueOf(100)
      },
      {
         TaskField.RESUME,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(20),
         Integer.valueOf(99)
      },
      {
         TaskField.FREE_SLACK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(24),
         Integer.valueOf(21)
      },
      {
         TaskField.START_SLACK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(28),
         Integer.valueOf(438)
      },
      {
         TaskField.FINISH_SLACK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(32),
         Integer.valueOf(439)
      },
      {
         TaskField.OUTLINE_LEVEL,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(40),
         Integer.valueOf(249)
      },
      {
         TaskField.DURATION_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(58),
         Integer.valueOf(152)
      },
      {
         TaskField.DURATION,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(60),
         Integer.valueOf(29)
      },
      {
         TaskField.ACTUAL_DURATION_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(64),
         Integer.valueOf(181)
      },
      {
         TaskField.ACTUAL_DURATION,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(66),
         Integer.valueOf(28)
      },
      {
         TaskField.REMAINING_DURATION,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(70),
         Integer.valueOf(31)
      },
      {
         TaskField.BASELINE_DURATION,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(74),
         Integer.valueOf(27)
      },
      {
         TaskField.BASELINE_DURATION_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(78),
         Integer.valueOf(179)
      },
      {
         TaskField.CONSTRAINT_TYPE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(80),
         Integer.valueOf(17)
      },
      {
         TaskField.LEVELING_DELAY,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(82),
         Integer.valueOf(20)
      },
      {
         TaskField.LEVELING_DELAY_UNITS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(86),
         Integer.valueOf(178)
      },
      {
         TaskField.START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(88),
         Integer.valueOf(35)
      },
      {
         TaskField.FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(92),
         Integer.valueOf(36)
      },
      {
         TaskField.ACTUAL_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(96),
         Integer.valueOf(41)
      },
      {
         TaskField.ACTUAL_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(100),
         Integer.valueOf(42)
      },
      {
         TaskField.BASELINE_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(104),
         Integer.valueOf(43)
      },
      {
         TaskField.BASELINE_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(108),
         Integer.valueOf(44)
      },
      {
         TaskField.CONSTRAINT_DATE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(112),
         Integer.valueOf(18)
      },
      {
         TaskField.PRIORITY,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(120),
         Integer.valueOf(25)
      },
      {
         TaskField.PERCENT_COMPLETE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(122),
         Integer.valueOf(32)
      },
      {
         TaskField.PERCENT_WORK_COMPLETE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(124),
         Integer.valueOf(33)
      },
      {
         TaskField.TYPE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(126),
         Integer.valueOf(128)
      },
      {
         TaskField.FIXED_COST_ACCRUAL,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(128),
         Integer.valueOf(200)
      },
      {
         TaskField.CREATED,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(130),
         Integer.valueOf(93)
      },
      {
         TaskField.RECURRING,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(134),
         Integer.valueOf(202)
      },
      {
         TaskField.PRELEVELED_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(136),
         Integer.valueOf(369)
      },
      {
         TaskField.PRELEVELED_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(140),
         Integer.valueOf(370)
      },
      {
         TaskField.EARLY_START,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(148),
         Integer.valueOf(37)
      },
      {
         TaskField.LATE_FINISH,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(152),
         Integer.valueOf(40)
      },
      {
         TaskField.SUMMARY_PROGRESS,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(156),
         Integer.valueOf(387)
      },
      {
         TaskField.DEADLINE,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(164),
         Integer.valueOf(437)
      },
      {
         TaskField.WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(168),
         Integer.valueOf(0)
      },
      {
         TaskField.BASELINE_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(176),
         Integer.valueOf(1)
      },
      {
         TaskField.ACTUAL_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(184),
         Integer.valueOf(2)
      },
      {
         TaskField.REMAINING_WORK,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(192),
         Integer.valueOf(4)
      },
      {
         TaskField.COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(200),
         Integer.valueOf(5)
      },
      {
         TaskField.FIXED_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(208),
         Integer.valueOf(8)
      },
      {
         TaskField.ACTUAL_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(216),
         Integer.valueOf(7)
      },
      {
         TaskField.REMAINING_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(224),
         Integer.valueOf(10)
      },
      {
         TaskField.BASELINE_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(232),
         Integer.valueOf(6)
      },
      {
         TaskField.BASELINE_FIXED_COST,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(256),
         Integer.valueOf(480)
      },
      {
         TaskField.ACTUAL_OVERTIME_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(164)
      },
      {
         TaskField.REMAINING_OVERTIME_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(165)
      },
      {
         TaskField.OVERTIME_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(168)
      },
      {
         TaskField.ACTUAL_OVERTIME_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(169)
      },
      {
         TaskField.REMAINING_OVERTIME_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(170)
      },
      {
         TaskField.SUBPROJECT_TASKS_UNIQUEID_OFFSET,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(458)
      },
      {
         TaskField.SUBPROJECT_UNIQUE_TASK_ID,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(242)
      },
      {
         TaskField.WBS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(16)
      },
      {
         TaskField.NAME,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(14)
      },
      {
         TaskField.CONTACT,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(112)
      },
      {
         TaskField.TEXT1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(51)
      },
      {
         TaskField.TEXT2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(54)
      },
      {
         TaskField.TEXT3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(57)
      },
      {
         TaskField.TEXT4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(60)
      },
      {
         TaskField.TEXT5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(63)
      },
      {
         TaskField.TEXT6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(66)
      },
      {
         TaskField.TEXT7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(67)
      },
      {
         TaskField.TEXT8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(68)
      },
      {
         TaskField.TEXT9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(69)
      },
      {
         TaskField.TEXT10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(70)
      },
      {
         TaskField.START1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(52)
      },
      {
         TaskField.FINISH1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(53)
      },
      {
         TaskField.START2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(55)
      },
      {
         TaskField.FINISH2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(56)
      },
      {
         TaskField.START3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(58)
      },
      {
         TaskField.FINISH3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(59)
      },
      {
         TaskField.START4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(61)
      },
      {
         TaskField.FINISH4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(62)
      },
      {
         TaskField.START5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(64)
      },
      {
         TaskField.FINISH5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(65)
      },
      {
         TaskField.START6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(282)
      },
      {
         TaskField.FINISH6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(283)
      },
      {
         TaskField.START7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(284)
      },
      {
         TaskField.FINISH7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(285)
      },
      {
         TaskField.START8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(286)
      },
      {
         TaskField.FINISH8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(287)
      },
      {
         TaskField.START9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(288)
      },
      {
         TaskField.FINISH9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(289)
      },
      {
         TaskField.START10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(290)
      },
      {
         TaskField.FINISH10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(291)
      },
      {
         TaskField.NUMBER1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(87)
      },
      {
         TaskField.NUMBER2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(88)
      },
      {
         TaskField.NUMBER3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(89)
      },
      {
         TaskField.NUMBER4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(90)
      },
      {
         TaskField.NUMBER5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(91)
      },
      {
         TaskField.NUMBER6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(302)
      },
      {
         TaskField.NUMBER7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(303)
      },
      {
         TaskField.NUMBER8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(304)
      },
      {
         TaskField.NUMBER9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(305)
      },
      {
         TaskField.NUMBER10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(306)
      },
      {
         TaskField.DURATION1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(103)
      },
      {
         TaskField.DURATION1_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(183)
      },
      {
         TaskField.DURATION2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(104)
      },
      {
         TaskField.DURATION2_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(184)
      },
      {
         TaskField.DURATION3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(105)
      },
      {
         TaskField.DURATION3_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(185)
      },
      {
         TaskField.DURATION4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(275)
      },
      {
         TaskField.DURATION4_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(337)
      },
      {
         TaskField.DURATION5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(276)
      },
      {
         TaskField.DURATION5_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(338)
      },
      {
         TaskField.DURATION6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(277)
      },
      {
         TaskField.DURATION6_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(339)
      },
      {
         TaskField.DURATION7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(278)
      },
      {
         TaskField.DURATION7_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(340)
      },
      {
         TaskField.DURATION8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(279)
      },
      {
         TaskField.DURATION8_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(341)
      },
      {
         TaskField.DURATION9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(280)
      },
      {
         TaskField.DURATION9_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(342)
      },
      {
         TaskField.DURATION10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(281)
      },
      {
         TaskField.DURATION10_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(343)
      },
      {
         TaskField.RECURRING_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(203)
      },
      {
         TaskField.SUBPROJECT_TASK_ID,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(255)
      },
      {
         TaskField.DATE1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(265)
      },
      {
         TaskField.DATE2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(266)
      },
      {
         TaskField.DATE3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(267)
      },
      {
         TaskField.DATE4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(268)
      },
      {
         TaskField.DATE5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(269)
      },
      {
         TaskField.DATE6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(270)
      },
      {
         TaskField.DATE7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(271)
      },
      {
         TaskField.DATE8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(272)
      },
      {
         TaskField.DATE9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(273)
      },
      {
         TaskField.DATE10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(274)
      },
      {
         TaskField.TEXT11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(317)
      },
      {
         TaskField.TEXT12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(318)
      },
      {
         TaskField.TEXT13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(319)
      },
      {
         TaskField.TEXT14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(320)
      },
      {
         TaskField.TEXT15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(321)
      },
      {
         TaskField.TEXT16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(322)
      },
      {
         TaskField.TEXT17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(323)
      },
      {
         TaskField.TEXT18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(324)
      },
      {
         TaskField.TEXT19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(325)
      },
      {
         TaskField.TEXT20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(326)
      },
      {
         TaskField.TEXT21,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(327)
      },
      {
         TaskField.TEXT22,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(328)
      },
      {
         TaskField.TEXT23,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(329)
      },
      {
         TaskField.TEXT24,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(330)
      },
      {
         TaskField.TEXT25,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(331)
      },
      {
         TaskField.TEXT26,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(332)
      },
      {
         TaskField.TEXT27,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(333)
      },
      {
         TaskField.TEXT28,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(334)
      },
      {
         TaskField.TEXT29,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(335)
      },
      {
         TaskField.TEXT30,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(336)
      },
      {
         TaskField.NUMBER11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(307)
      },
      {
         TaskField.NUMBER12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(308)
      },
      {
         TaskField.NUMBER13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(309)
      },
      {
         TaskField.NUMBER14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(310)
      },
      {
         TaskField.NUMBER15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(311)
      },
      {
         TaskField.NUMBER16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(312)
      },
      {
         TaskField.NUMBER17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(313)
      },
      {
         TaskField.NUMBER18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(314)
      },
      {
         TaskField.NUMBER19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(315)
      },
      {
         TaskField.NUMBER20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(316)
      },
      {
         TaskField.OUTLINE_CODE1_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(417)
      },
      {
         TaskField.OUTLINE_CODE2_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(419)
      },
      {
         TaskField.OUTLINE_CODE3_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(421)
      },
      {
         TaskField.OUTLINE_CODE4_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(423)
      },
      {
         TaskField.OUTLINE_CODE5_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(425)
      },
      {
         TaskField.OUTLINE_CODE6_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(427)
      },
      {
         TaskField.OUTLINE_CODE7_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(429)
      },
      {
         TaskField.OUTLINE_CODE8_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(431)
      },
      {
         TaskField.OUTLINE_CODE9_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(433)
      },
      {
         TaskField.OUTLINE_CODE10_INDEX,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(435)
      },
      {
         TaskField.FLAG1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(72)
      },
      {
         TaskField.FLAG2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(73)
      },
      {
         TaskField.FLAG3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(74)
      },
      {
         TaskField.FLAG4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(75)
      },
      {
         TaskField.FLAG5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(76)
      },
      {
         TaskField.FLAG6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(77)
      },
      {
         TaskField.FLAG7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(78)
      },
      {
         TaskField.FLAG8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(79)
      },
      {
         TaskField.FLAG9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(80)
      },
      {
         TaskField.FLAG10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(81)
      },
      {
         TaskField.FLAG11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(292)
      },
      {
         TaskField.FLAG12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(293)
      },
      {
         TaskField.FLAG13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(294)
      },
      {
         TaskField.FLAG14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(295)
      },
      {
         TaskField.FLAG15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(296)
      },
      {
         TaskField.FLAG16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(297)
      },
      {
         TaskField.FLAG17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(298)
      },
      {
         TaskField.FLAG18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(299)
      },
      {
         TaskField.FLAG19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(300)
      },
      {
         TaskField.FLAG20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(301)
      },
      {
         TaskField.HYPERLINK_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(215)
      },
      {
         TaskField.COST1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(106)
      },
      {
         TaskField.COST2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(107)
      },
      {
         TaskField.COST3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(108)
      },
      {
         TaskField.COST4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(258)
      },
      {
         TaskField.COST5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(259)
      },
      {
         TaskField.COST6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(260)
      },
      {
         TaskField.COST7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(261)
      },
      {
         TaskField.COST8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(262)
      },
      {
         TaskField.COST9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(263)
      },
      {
         TaskField.COST10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(264)
      },
      {
         TaskField.NOTES,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(15)
      },
      {
         TaskField.SUBPROJECT_FILE,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(26)
      },
      {
         TaskField.GUID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(0),
         Integer.valueOf(1143)
      },
      {
         TaskField.BASELINE_FIXED_COST_ACCRUAL,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(44),
         Integer.valueOf(1173)
      },
      {
         TaskField.ENTERPRISE_DATA,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(481)
      },
      {
         TaskField.BASELINE1_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(482)
      },
      {
         TaskField.BASELINE1_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(483)
      },
      {
         TaskField.BASELINE1_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(484)
      },
      {
         TaskField.BASELINE1_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(485)
      },
      {
         TaskField.BASELINE1_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(487)
      },
      {
         TaskField.BASELINE1_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(488)
      },
      {
         TaskField.BASELINE1_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(489)
      },
      {
         TaskField.BASELINE2_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(493)
      },
      {
         TaskField.BASELINE2_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(494)
      },
      {
         TaskField.BASELINE2_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(495)
      },
      {
         TaskField.BASELINE2_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(496)
      },
      {
         TaskField.BASELINE2_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(498)
      },
      {
         TaskField.BASELINE2_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(499)
      },
      {
         TaskField.BASELINE2_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(500)
      },
      {
         TaskField.BASELINE3_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(504)
      },
      {
         TaskField.BASELINE3_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(505)
      },
      {
         TaskField.BASELINE3_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(506)
      },
      {
         TaskField.BASELINE3_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(507)
      },
      {
         TaskField.BASELINE3_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(509)
      },
      {
         TaskField.BASELINE3_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(510)
      },
      {
         TaskField.BASELINE3_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(511)
      },
      {
         TaskField.BASELINE4_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(515)
      },
      {
         TaskField.BASELINE4_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(516)
      },
      {
         TaskField.BASELINE4_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(517)
      },
      {
         TaskField.BASELINE4_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(518)
      },
      {
         TaskField.BASELINE4_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(520)
      },
      {
         TaskField.BASELINE4_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(521)
      },
      {
         TaskField.BASELINE4_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(522)
      },
      {
         TaskField.BASELINE5_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(526)
      },
      {
         TaskField.BASELINE5_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(527)
      },
      {
         TaskField.BASELINE5_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(528)
      },
      {
         TaskField.BASELINE5_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(529)
      },
      {
         TaskField.BASELINE5_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(531)
      },
      {
         TaskField.BASELINE5_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(532)
      },
      {
         TaskField.BASELINE5_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(533)
      },
      {
         TaskField.BASELINE6_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(544)
      },
      {
         TaskField.BASELINE6_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(545)
      },
      {
         TaskField.BASELINE6_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(546)
      },
      {
         TaskField.BASELINE6_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(547)
      },
      {
         TaskField.BASELINE6_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(549)
      },
      {
         TaskField.BASELINE6_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(550)
      },
      {
         TaskField.BASELINE6_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(551)
      },
      {
         TaskField.BASELINE7_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(555)
      },
      {
         TaskField.BASELINE7_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(556)
      },
      {
         TaskField.BASELINE7_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(557)
      },
      {
         TaskField.BASELINE7_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(558)
      },
      {
         TaskField.BASELINE7_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(560)
      },
      {
         TaskField.BASELINE7_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(561)
      },
      {
         TaskField.BASELINE7_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(562)
      },
      {
         TaskField.BASELINE8_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(566)
      },
      {
         TaskField.BASELINE8_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(567)
      },
      {
         TaskField.BASELINE8_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(568)
      },
      {
         TaskField.BASELINE8_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(569)
      },
      {
         TaskField.BASELINE8_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(571)
      },
      {
         TaskField.BASELINE8_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(572)
      },
      {
         TaskField.BASELINE8_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(573)
      },
      {
         TaskField.BASELINE9_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(577)
      },
      {
         TaskField.BASELINE9_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(578)
      },
      {
         TaskField.BASELINE9_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(579)
      },
      {
         TaskField.BASELINE9_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(580)
      },
      {
         TaskField.BASELINE9_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(582)
      },
      {
         TaskField.BASELINE9_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(583)
      },
      {
         TaskField.BASELINE9_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(584)
      },
      {
         TaskField.BASELINE10_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(588)
      },
      {
         TaskField.BASELINE10_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(589)
      },
      {
         TaskField.BASELINE10_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(590)
      },
      {
         TaskField.BASELINE10_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(591)
      },
      {
         TaskField.BASELINE10_DURATION,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(593)
      },
      {
         TaskField.BASELINE10_DURATION_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(594)
      },
      {
         TaskField.BASELINE10_FIXED_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(595)
      },
      {
         TaskField.ENTERPRISE_COST1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(599)
      },
      {
         TaskField.ENTERPRISE_COST2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(600)
      },
      {
         TaskField.ENTERPRISE_COST3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(601)
      },
      {
         TaskField.ENTERPRISE_COST4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(602)
      },
      {
         TaskField.ENTERPRISE_COST5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(603)
      },
      {
         TaskField.ENTERPRISE_COST6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(604)
      },
      {
         TaskField.ENTERPRISE_COST7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(605)
      },
      {
         TaskField.ENTERPRISE_COST8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(606)
      },
      {
         TaskField.ENTERPRISE_COST9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(607)
      },
      {
         TaskField.ENTERPRISE_COST10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(608)
      },
      {
         TaskField.ENTERPRISE_DATE1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(609)
      },
      {
         TaskField.ENTERPRISE_DATE2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(610)
      },
      {
         TaskField.ENTERPRISE_DATE3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(611)
      },
      {
         TaskField.ENTERPRISE_DATE4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(612)
      },
      {
         TaskField.ENTERPRISE_DATE5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(613)
      },
      {
         TaskField.ENTERPRISE_DATE6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(614)
      },
      {
         TaskField.ENTERPRISE_DATE7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(615)
      },
      {
         TaskField.ENTERPRISE_DATE8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(616)
      },
      {
         TaskField.ENTERPRISE_DATE9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(617)
      },
      {
         TaskField.ENTERPRISE_DATE10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(618)
      },
      {
         TaskField.ENTERPRISE_DATE11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(619)
      },
      {
         TaskField.ENTERPRISE_DATE12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(620)
      },
      {
         TaskField.ENTERPRISE_DATE13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(621)
      },
      {
         TaskField.ENTERPRISE_DATE14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(622)
      },
      {
         TaskField.ENTERPRISE_DATE15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(623)
      },
      {
         TaskField.ENTERPRISE_DATE16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(624)
      },
      {
         TaskField.ENTERPRISE_DATE17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(625)
      },
      {
         TaskField.ENTERPRISE_DATE18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(626)
      },
      {
         TaskField.ENTERPRISE_DATE19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(627)
      },
      {
         TaskField.ENTERPRISE_DATE20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(628)
      },
      {
         TaskField.ENTERPRISE_DATE21,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(629)
      },
      {
         TaskField.ENTERPRISE_DATE22,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(630)
      },
      {
         TaskField.ENTERPRISE_DATE23,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(631)
      },
      {
         TaskField.ENTERPRISE_DATE24,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(632)
      },
      {
         TaskField.ENTERPRISE_DATE25,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(633)
      },
      {
         TaskField.ENTERPRISE_DATE26,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(634)
      },
      {
         TaskField.ENTERPRISE_DATE27,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(635)
      },
      {
         TaskField.ENTERPRISE_DATE28,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(636)
      },
      {
         TaskField.ENTERPRISE_DATE29,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(637)
      },
      {
         TaskField.ENTERPRISE_DATE30,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(638)
      },
      {
         TaskField.ENTERPRISE_DURATION1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(639)
      },
      {
         TaskField.ENTERPRISE_DURATION1_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(649)
      },
      {
         TaskField.ENTERPRISE_DURATION2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(640)
      },
      {
         TaskField.ENTERPRISE_DURATION2_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(650)
      },
      {
         TaskField.ENTERPRISE_DURATION3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(641)
      },
      {
         TaskField.ENTERPRISE_DURATION3_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(651)
      },
      {
         TaskField.ENTERPRISE_DURATION4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(642)
      },
      {
         TaskField.ENTERPRISE_DURATION4_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(652)
      },
      {
         TaskField.ENTERPRISE_DURATION5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(643)
      },
      {
         TaskField.ENTERPRISE_DURATION5_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(653)
      },
      {
         TaskField.ENTERPRISE_DURATION6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(644)
      },
      {
         TaskField.ENTERPRISE_DURATION6_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(654)
      },
      {
         TaskField.ENTERPRISE_DURATION7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(645)
      },
      {
         TaskField.ENTERPRISE_DURATION7_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(655)
      },
      {
         TaskField.ENTERPRISE_DURATION8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(646)
      },
      {
         TaskField.ENTERPRISE_DURATION8_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(656)
      },
      {
         TaskField.ENTERPRISE_DURATION9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(647)
      },
      {
         TaskField.ENTERPRISE_DURATION9_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(657)
      },
      {
         TaskField.ENTERPRISE_DURATION10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(648)
      },
      {
         TaskField.ENTERPRISE_DURATION10_UNITS,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(658)
      },
      {
         TaskField.ENTERPRISE_FLAG1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(659)
      },
      {
         TaskField.ENTERPRISE_FLAG2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(660)
      },
      {
         TaskField.ENTERPRISE_FLAG3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(661)
      },
      {
         TaskField.ENTERPRISE_FLAG4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(662)
      },
      {
         TaskField.ENTERPRISE_FLAG5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(663)
      },
      {
         TaskField.ENTERPRISE_FLAG6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(664)
      },
      {
         TaskField.ENTERPRISE_FLAG7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(665)
      },
      {
         TaskField.ENTERPRISE_FLAG8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(666)
      },
      {
         TaskField.ENTERPRISE_FLAG9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(667)
      },
      {
         TaskField.ENTERPRISE_FLAG10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(668)
      },
      {
         TaskField.ENTERPRISE_FLAG11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(669)
      },
      {
         TaskField.ENTERPRISE_FLAG12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(670)
      },
      {
         TaskField.ENTERPRISE_FLAG13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(671)
      },
      {
         TaskField.ENTERPRISE_FLAG14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(672)
      },
      {
         TaskField.ENTERPRISE_FLAG15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(673)
      },
      {
         TaskField.ENTERPRISE_FLAG16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(674)
      },
      {
         TaskField.ENTERPRISE_FLAG17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(675)
      },
      {
         TaskField.ENTERPRISE_FLAG18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(676)
      },
      {
         TaskField.ENTERPRISE_FLAG19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(677)
      },
      {
         TaskField.ENTERPRISE_FLAG20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(678)
      },
      {
         TaskField.ENTERPRISE_NUMBER1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(699)
      },
      {
         TaskField.ENTERPRISE_NUMBER2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(700)
      },
      {
         TaskField.ENTERPRISE_NUMBER3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(701)
      },
      {
         TaskField.ENTERPRISE_NUMBER4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(702)
      },
      {
         TaskField.ENTERPRISE_NUMBER5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(703)
      },
      {
         TaskField.ENTERPRISE_NUMBER6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(704)
      },
      {
         TaskField.ENTERPRISE_NUMBER7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(705)
      },
      {
         TaskField.ENTERPRISE_NUMBER8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(706)
      },
      {
         TaskField.ENTERPRISE_NUMBER9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(707)
      },
      {
         TaskField.ENTERPRISE_NUMBER10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(708)
      },
      {
         TaskField.ENTERPRISE_NUMBER11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(709)
      },
      {
         TaskField.ENTERPRISE_NUMBER12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(710)
      },
      {
         TaskField.ENTERPRISE_NUMBER13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(711)
      },
      {
         TaskField.ENTERPRISE_NUMBER14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(712)
      },
      {
         TaskField.ENTERPRISE_NUMBER15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(713)
      },
      {
         TaskField.ENTERPRISE_NUMBER16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(714)
      },
      {
         TaskField.ENTERPRISE_NUMBER17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(715)
      },
      {
         TaskField.ENTERPRISE_NUMBER18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(716)
      },
      {
         TaskField.ENTERPRISE_NUMBER19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(717)
      },
      {
         TaskField.ENTERPRISE_NUMBER20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(718)
      },
      {
         TaskField.ENTERPRISE_NUMBER21,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(719)
      },
      {
         TaskField.ENTERPRISE_NUMBER22,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(720)
      },
      {
         TaskField.ENTERPRISE_NUMBER23,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(721)
      },
      {
         TaskField.ENTERPRISE_NUMBER24,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(722)
      },
      {
         TaskField.ENTERPRISE_NUMBER25,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(723)
      },
      {
         TaskField.ENTERPRISE_NUMBER26,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(724)
      },
      {
         TaskField.ENTERPRISE_NUMBER27,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(725)
      },
      {
         TaskField.ENTERPRISE_NUMBER28,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(726)
      },
      {
         TaskField.ENTERPRISE_NUMBER29,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(727)
      },
      {
         TaskField.ENTERPRISE_NUMBER30,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(728)
      },
      {
         TaskField.ENTERPRISE_NUMBER31,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(729)
      },
      {
         TaskField.ENTERPRISE_NUMBER32,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(730)
      },
      {
         TaskField.ENTERPRISE_NUMBER33,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(731)
      },
      {
         TaskField.ENTERPRISE_NUMBER34,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(732)
      },
      {
         TaskField.ENTERPRISE_NUMBER35,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(733)
      },
      {
         TaskField.ENTERPRISE_NUMBER36,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(734)
      },
      {
         TaskField.ENTERPRISE_NUMBER37,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(735)
      },
      {
         TaskField.ENTERPRISE_NUMBER38,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(736)
      },
      {
         TaskField.ENTERPRISE_NUMBER39,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(737)
      },
      {
         TaskField.ENTERPRISE_NUMBER40,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(738)
      },
      {
         TaskField.ENTERPRISE_TEXT1,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(799)
      },
      {
         TaskField.ENTERPRISE_TEXT2,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(800)
      },
      {
         TaskField.ENTERPRISE_TEXT3,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(801)
      },
      {
         TaskField.ENTERPRISE_TEXT4,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(802)
      },
      {
         TaskField.ENTERPRISE_TEXT5,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(803)
      },
      {
         TaskField.ENTERPRISE_TEXT6,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(804)
      },
      {
         TaskField.ENTERPRISE_TEXT7,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(805)
      },
      {
         TaskField.ENTERPRISE_TEXT8,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(806)
      },
      {
         TaskField.ENTERPRISE_TEXT9,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(807)
      },
      {
         TaskField.ENTERPRISE_TEXT10,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(808)
      },
      {
         TaskField.ENTERPRISE_TEXT11,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(809)
      },
      {
         TaskField.ENTERPRISE_TEXT12,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(810)
      },
      {
         TaskField.ENTERPRISE_TEXT13,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(811)
      },
      {
         TaskField.ENTERPRISE_TEXT14,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(812)
      },
      {
         TaskField.ENTERPRISE_TEXT15,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(813)
      },
      {
         TaskField.ENTERPRISE_TEXT16,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(814)
      },
      {
         TaskField.ENTERPRISE_TEXT17,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(815)
      },
      {
         TaskField.ENTERPRISE_TEXT18,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(816)
      },
      {
         TaskField.ENTERPRISE_TEXT19,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(817)
      },
      {
         TaskField.ENTERPRISE_TEXT20,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(818)
      },
      {
         TaskField.ENTERPRISE_TEXT21,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(819)
      },
      {
         TaskField.ENTERPRISE_TEXT22,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(820)
      },
      {
         TaskField.ENTERPRISE_TEXT23,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(821)
      },
      {
         TaskField.ENTERPRISE_TEXT24,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(822)
      },
      {
         TaskField.ENTERPRISE_TEXT25,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(823)
      },
      {
         TaskField.ENTERPRISE_TEXT26,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(824)
      },
      {
         TaskField.ENTERPRISE_TEXT27,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(825)
      },
      {
         TaskField.ENTERPRISE_TEXT28,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(826)
      },
      {
         TaskField.ENTERPRISE_TEXT29,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(827)
      },
      {
         TaskField.ENTERPRISE_TEXT30,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(828)
      },
      {
         TaskField.ENTERPRISE_TEXT31,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(829)
      },
      {
         TaskField.ENTERPRISE_TEXT32,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(830)
      },
      {
         TaskField.ENTERPRISE_TEXT33,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(831)
      },
      {
         TaskField.ENTERPRISE_TEXT34,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(832)
      },
      {
         TaskField.ENTERPRISE_TEXT35,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(833)
      },
      {
         TaskField.ENTERPRISE_TEXT36,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(834)
      },
      {
         TaskField.ENTERPRISE_TEXT37,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(835)
      },
      {
         TaskField.ENTERPRISE_TEXT38,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(836)
      },
      {
         TaskField.ENTERPRISE_TEXT39,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(837)
      },
      {
         TaskField.ENTERPRISE_TEXT40,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(838)
      },
      {
         TaskField.PHYSICAL_PERCENT_COMPLETE,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1119)
      },
      {
         TaskField.EARNED_VALUE_METHOD,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1122)
      },
      {
         TaskField.BASELINE_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1174)
      },
      {
         TaskField.BASELINE_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1175)
      },
      {
         TaskField.BASELINE_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1176)
      },
      {
         TaskField.BASELINE_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1177)
      },
      {
         TaskField.BASELINE1_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1180)
      },
      {
         TaskField.BASELINE1_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1181)
      },
      {
         TaskField.BASELINE1_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1182)
      },
      {
         TaskField.BASELINE1_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1183)
      },
      {
         TaskField.BASELINE1_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1184)
      },
      {
         TaskField.BASELINE2_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1187)
      },
      {
         TaskField.BASELINE2_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1188)
      },
      {
         TaskField.BASELINE2_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1189)
      },
      {
         TaskField.BASELINE2_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1190)
      },
      {
         TaskField.BASELINE2_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1191)
      },
      {
         TaskField.BASELINE3_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1194)
      },
      {
         TaskField.BASELINE3_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1195)
      },
      {
         TaskField.BASELINE3_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1196)
      },
      {
         TaskField.BASELINE3_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1197)
      },
      {
         TaskField.BASELINE3_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1198)
      },
      {
         TaskField.BASELINE4_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1201)
      },
      {
         TaskField.BASELINE4_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1202)
      },
      {
         TaskField.BASELINE4_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1203)
      },
      {
         TaskField.BASELINE4_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1204)
      },
      {
         TaskField.BASELINE4_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1205)
      },
      {
         TaskField.BASELINE5_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1208)
      },
      {
         TaskField.BASELINE5_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1209)
      },
      {
         TaskField.BASELINE5_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1210)
      },
      {
         TaskField.BASELINE5_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1211)
      },
      {
         TaskField.BASELINE5_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1212)
      },
      {
         TaskField.BASELINE6_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1215)
      },
      {
         TaskField.BASELINE6_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1216)
      },
      {
         TaskField.BASELINE6_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1217)
      },
      {
         TaskField.BASELINE6_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1218)
      },
      {
         TaskField.BASELINE6_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1219)
      },
      {
         TaskField.BASELINE7_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1222)
      },
      {
         TaskField.BASELINE7_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1223)
      },
      {
         TaskField.BASELINE7_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1224)
      },
      {
         TaskField.BASELINE7_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1225)
      },
      {
         TaskField.BASELINE7_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1226)
      },
      {
         TaskField.BASELINE8_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1229)
      },
      {
         TaskField.BASELINE8_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1230)
      },
      {
         TaskField.BASELINE8_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1231)
      },
      {
         TaskField.BASELINE8_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1232)
      },
      {
         TaskField.BASELINE8_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1233)
      },
      {
         TaskField.BASELINE9_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1236)
      },
      {
         TaskField.BASELINE9_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1237)
      },
      {
         TaskField.BASELINE9_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1238)
      },
      {
         TaskField.BASELINE9_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1239)
      },
      {
         TaskField.BASELINE9_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1240)
      },
      {
         TaskField.BASELINE10_FIXED_COST_ACCRUAL,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1243)
      },
      {
         TaskField.BASELINE10_DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1244)
      },
      {
         TaskField.BASELINE10_DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1245)
      },
      {
         TaskField.BASELINE10_BUDGET_WORK,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1246)
      },
      {
         TaskField.BASELINE10_BUDGET_COST,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1247)
      },
      {
         TaskField.DELIVERABLE_GUID,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1146)
      },
      {
         TaskField.DELIVERABLE_NAME,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1276)
      },
      {
         TaskField.DELIVERABLE_START,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1152)
      },
      {
         TaskField.DELIVERABLE_FINISH,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1153)
      },
      {
         TaskField.DELIVERABLE_TYPE,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1147)
      },
      {
         TaskField.TASK_CALENDAR_GUID,
         FieldLocation.VAR_DATA,
         Integer.valueOf(65535),
         Integer.valueOf(1144)
      },
      {
         TaskField.PARENT_TASK_UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(36),
         Integer.valueOf(160)
      },
      {
         TaskField.CALENDAR_UNIQUE_ID,
         FieldLocation.FIXED_DATA,
         Integer.valueOf(160),
         Integer.valueOf(401)
      }
   };
}
